const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const concepts=new Map(ATLAS_DATA.concepts.map(c=>[c.id,c]));
const labels={validated:"検証済み日本語版",translated:"日本語使用例あり",none:"日本語版なし",open:"掲載・利用可",research:"研究利用可",unknown:"利用条件未確認",permission:"申請が必要","research-use":"研究利用可","permission-required":"申請が必要",original:"原版",short:"短縮版"};
const state={compare:new Set()};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const scholarUrl=s=>`https://scholar.google.com/scholar?q=${encodeURIComponent(`"${s.name}" ${s.authors.join(" ")} ${s.year}`)}`;
const doiUrl=s=>s.doi?`https://doi.org/${encodeURIComponent(s.doi.trim())}`:"";
function sourceLinks(s){return `<div class="source-links"><a href="${scholarUrl(s)}" target="_blank" rel="noopener noreferrer">Google Scholar ↗</a>${s.doi?`<a href="${doiUrl(s)}" target="_blank" rel="noopener noreferrer">DOI ↗</a>`:`<span>DOI未登録</span>`}</div>`}
function init(){
  [...new Set(ATLAS_DATA.concepts.map(c=>c.domain))].forEach(d=>$("#domain-filter").insertAdjacentHTML("beforeend",`<option>${esc(d)}</option>`));
  ["query","domain-filter","japanese-filter","permission-filter","items-filter"].forEach(id=>$("#"+id).addEventListener(id==="query"?"input":"change",renderScales));
  $("#clear-filters").onclick=()=>{$("#query").value="";$$('.filters select').forEach(x=>x.value="");renderScales()};
  $$(".tab").forEach(b=>b.onclick=()=>showView(b.dataset.view));
  $(".dialog-close").onclick=()=>$("#detail-dialog").close();
  $("#detail-dialog").onclick=e=>{if(e.target===$("#detail-dialog"))e.target.close()};
  renderScales();renderConcepts();renderCompare();
}
function showView(name){$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${name}`));}
function filtered(){const q=$("#query").value.trim().toLowerCase(),d=$("#domain-filter").value,j=$("#japanese-filter").value,p=$("#permission-filter").value,max=Number($("#items-filter").value||Infinity);return ATLAS_DATA.scales.filter(s=>{const c=concepts.get(s.conceptId);const hay=[s.name,s.abbreviation,...s.authors,...s.targetPopulation,c.nameJa,c.nameEn].join(' ').toLowerCase();const jm=!j||(j==='available'?s.japaneseVersionStatus!=='none':s.japaneseVersionStatus===j);const pm=!p||(p==='research'?s.usagePermission==='research-use':p==='permission'?s.usagePermission==='permission-required':s.usagePermission===p);return(!q||hay.includes(q))&&(!d||c.domain===d)&&jm&&pm&&s.itemCount<=max})}
function scaleCard(s){const c=concepts.get(s.conceptId),selected=state.compare.has(s.id);return `<article class="scale-card"><p class="sub">${esc(c.nameJa)} / ${esc(c.nameEn)}</p><h3>${esc(s.name)}</h3><p class="sub">${esc(s.abbreviation)} ・ ${s.year}年 ・ サンプル</p><div class="badges"><span class="badge">${s.itemCount}項目</span><span class="badge">${esc(labels[s.versionType])}</span><span class="badge">${esc(labels[s.japaneseVersionStatus])}</span><span class="badge warn">${esc(labels[s.usagePermission])}</span></div>${sourceLinks(s)}<div class="card-actions"><button class="detail-button" data-scale="${s.id}">詳細を見る</button><button class="compare-button ${selected?'selected':''}" data-compare="${s.id}">${selected?'比較から外す':'比較に追加'}</button></div></article>`}
function bindCards(){$$('[data-scale]').forEach(b=>b.onclick=()=>openScale(b.dataset.scale));$$('[data-compare]').forEach(b=>b.onclick=()=>toggleCompare(b.dataset.compare))}
function renderScales(){const a=filtered();$("#result-count").textContent=`${a.length}件（全${ATLAS_DATA.scales.length}件）`;$("#scale-list").innerHTML=a.map(scaleCard).join('')||'<div class="empty-state">条件に合う尺度がありません。</div>';bindCards()}
function renderConcepts(){$("#concept-list").innerHTML=ATLAS_DATA.concepts.map(c=>`<article class="concept-card" data-concept="${c.id}"><span class="badge">${esc(c.domain)}</span><h3>${esc(c.nameJa)}</h3><p class="sub">${esc(c.nameEn)}</p><p>${esc(c.definitionJa)}</p><p>${ATLAS_DATA.scales.filter(s=>s.conceptId===c.id).length}尺度</p></article>`).join('');$$('[data-concept]').forEach(x=>x.onclick=()=>openConcept(x.dataset.concept))}
function openScale(id){const s=ATLAS_DATA.scales.find(x=>x.id===id),c=concepts.get(s.conceptId);$("#detail-body").innerHTML=`<p class="sub">尺度詳細・サンプル</p><h2 class="detail-title">${esc(s.name)}</h2><p>${esc(c.nameJa)} / ${esc(c.nameEn)}</p><div class="sample-notice"><strong>注意：</strong>この文献情報は画面検証用です。原典として引用できません。</div><div class="detail-section detail-grid"><div><strong>略称</strong>${esc(s.abbreviation)}</div><div><strong>開発年</strong>${s.year}</div><div><strong>項目数</strong>${s.itemCount}</div><div><strong>回答形式</strong>${esc(s.responseFormat)}</div><div><strong>下位次元</strong>${esc(s.dimensions.join('、'))}</div><div><strong>対象者</strong>${esc(s.targetPopulation.join('、'))}</div><div><strong>日本語版</strong>${esc(labels[s.japaneseVersionStatus])}</div><div><strong>利用条件</strong>${esc(labels[s.usagePermission])}</div></div><div class="detail-section"><h3>原典・文献情報</h3><p><strong>${esc(s.sourceTitle||'原典タイトル未登録')}</strong><br><span class="sub">${esc(s.authors.join('、'))}（${s.year}）${s.journal?`・${esc(s.journal)}`:''}</span></p>${sourceLinks(s)}</div><div class="detail-section"><h3>尺度項目</h3><p>掲載していません。利用条件と原典を確認してください。</p></div>`;$("#detail-dialog").showModal()}
function openConcept(id){const c=concepts.get(id),related=c.relatedConcepts.map(x=>concepts.get(x)?.nameJa).filter(Boolean);$("#detail-body").innerHTML=`<p class="sub">概念詳細・サンプル</p><h2 class="detail-title">${esc(c.nameJa)}</h2><p class="sub">${esc(c.nameEn)}</p><div class="detail-section"><h3>定義</h3><p>${esc(c.definitionJa)}</p></div><div class="detail-section"><h3>関連概念</h3><p>${esc(related.join('、')||'未登録')}</p></div><div class="detail-section"><h3>関連尺度</h3>${ATLAS_DATA.scales.filter(s=>s.conceptId===id).map(s=>`<p><button class="text-button" data-modal-scale="${s.id}">${esc(s.name)}（${s.itemCount}項目）</button></p>`).join('')}</div>`;$("#detail-dialog").showModal();$$('[data-modal-scale]').forEach(b=>b.onclick=()=>openScale(b.dataset.modalScale))}
function toggleCompare(id){if(state.compare.has(id))state.compare.delete(id);else if(state.compare.size<4)state.compare.add(id);else return alert('比較できる尺度は最大4件です。');renderScales();renderCompare()}
function renderCompare(){const a=[...state.compare].map(id=>ATLAS_DATA.scales.find(s=>s.id===id));$("#compare-count").textContent=a.length;$("#compare-empty").hidden=!!a.length;$("#compare-table-wrap").hidden=!a.length;if(!a.length)return;const rows=[["概念",s=>concepts.get(s.conceptId).nameJa],["項目数",s=>s.itemCount],["下位次元",s=>s.dimensions.join('、')],["回答件法",s=>s.responseFormat],["対象者",s=>s.targetPopulation.join('、')],["日本語版",s=>labels[s.japaneseVersionStatus]],["利用条件",s=>labels[s.usagePermission]],["版",s=>labels[s.versionType]]];$("#compare-table").innerHTML=`<thead><tr><th>比較項目</th>${a.map(s=>`<th>${esc(s.name)}<br><button class="text-button" data-remove="${s.id}">外す</button></th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><th>${r[0]}</th>${a.map(s=>`<td>${esc(r[1](s))}</td>`).join('')}</tr>`).join('')}</tbody>`;$$('[data-remove]').forEach(b=>b.onclick=()=>toggleCompare(b.dataset.remove))}
init();
