// 初期実データ版（2026-07-13確認）。尺度項目本文は収録しない。
// DOI、原典、項目数、下位次元は原著論文または公式資料で確認。
const ATLAS_DATA = {
  meta: {
    version: "0.14.0",
    status: "initial-real-data",
    updated: "2026-07-13",
    scope: "30概念・41尺度",
  },

  concepts: [
    {
      id: "brand-experience",
      nameJa: "ブランド経験",
      nameEn: "Brand Experience",
      definitionJa: "ブランドに関連する刺激によって生じる感覚・感情・認知・行動上の反応。",
      domain: "ブランド・消費者経験",
      relatedConcepts: ["brand-attachment", "brand-personality", "consumer-brand-engagement"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1509/jmkg.73.3.52"],
    },
    {
      id: "brand-attachment",
      nameJa: "ブランド愛着",
      nameEn: "Brand Attachment",
      definitionJa: "ブランドと自己との結びつき、およびブランドに関する思考や感情の顕著性から捉える結合の強さ。",
      domain: "ブランド・消費者経験",
      relatedConcepts: ["brand-experience", "consumer-brand-engagement"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1509/jmkg.74.6.1"],
    },
    {
      id: "sense-of-agency",
      nameJa: "主体感",
      nameEn: "Sense of Agency",
      definitionJa: "自分が行為や経験の開始者・制御者であると感じる主観的経験。一般的信念を測る尺度と、特定状況での変化を測る尺度がある。",
      domain: "身体性・没入・主体感",
      relatedConcepts: ["presence", "flow"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.3389/fpsyg.2017.01552", "10.1016/j.concog.2013.04.003"],
    },
    {
      id: "presence",
      nameJa: "プレゼンス",
      nameEn: "Presence",
      definitionJa: "媒介された環境、とくに仮想環境やメディア環境の中に実際に存在しているように感じる経験。",
      domain: "身体性・没入・主体感",
      relatedConcepts: ["sense-of-agency", "flow"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1162/105474601300343612"],
    },
    {
      id: "flow",
      nameJa: "フロー",
      nameEn: "Flow",
      definitionJa: "活動へ深く集中し、行為と意識の融合、統制感、時間感覚の変化などを伴う最適経験。",
      domain: "身体性・没入・主体感",
      relatedConcepts: ["presence", "sense-of-agency"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1123/jsep.18.1.17", "10.1123/jsep.30.5.561"],
    },
    {
      id: "brand-personality",
      nameJa: "ブランド・パーソナリティ",
      nameEn: "Brand Personality",
      definitionJa: "消費者がブランドに結びつけて知覚する、人間の性格特性の集合。",
      domain: "ブランド・消費者経験",
      relatedConcepts: ["brand-experience", "brand-attachment"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1177/002224379703400304"],
    },
    {
      id: "service-quality",
      nameJa: "サービス品質",
      nameEn: "Service Quality",
      definitionJa: "顧客が期待するサービスと実際に知覚したサービスの差や、サービス提供の主要属性から捉える品質評価。",
      domain: "サービス・顧客関係",
      relatedConcepts: [],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: [],
    },
    {
      id: "market-orientation",
      nameJa: "市場志向",
      nameEn: "Market Orientation",
      definitionJa: "顧客の現在・将来ニーズに関する市場情報を組織全体で生成・共有し、組織的に反応する傾向。",
      domain: "戦略・組織能力",
      relatedConcepts: ["entrepreneurial-orientation"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1177/002224379303000406"],
    },
    {
      id: "organizational-identification",
      nameJa: "組織同一視",
      nameEn: "Organizational Identification",
      definitionJa: "自分と組織を一体のものとして知覚し、組織の成功や失敗を自分自身のものとして経験する程度。",
      domain: "組織行動・人的資源",
      relatedConcepts: [],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1002/job.4030130202"],
    },
    {
      id: "entrepreneurial-orientation",
      nameJa: "起業家志向",
      nameEn: "Entrepreneurial Orientation",
      definitionJa: "企業の戦略姿勢を、革新性、先行性、リスク志向などから捉える構成概念。",
      domain: "戦略・組織能力",
      relatedConcepts: ["market-orientation"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1002/smj.4250100107"],
    },
    {
      id: "consumer-brand-engagement",
      nameJa: "消費者ブランド・エンゲージメント",
      nameEn: "Consumer Brand Engagement",
      definitionJa: "ブランドとの相互作用における消費者の認知的処理、感情、行動的活性化からなる積極的関与。",
      domain: "ブランド・消費者経験",
      relatedConcepts: ["brand-experience", "brand-attachment"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1016/j.intmar.2013.12.002"],
    },
    {
      id: "brand-trust",
      nameJa: "ブランド信頼",
      nameEn: "Brand Trust",
      definitionJa: "ブランドが約束した価値を確実に提供し、問題時にも消費者利益を守ると期待できる程度。",
      domain: "ブランド・消費者経験",
      relatedConcepts: ["brand-attachment", "consumer-based-brand-equity"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1177/147078530304500103"],
    },
    {
      id: "customer-satisfaction",
      nameJa: "顧客満足",
      nameEn: "Customer Satisfaction",
      definitionJa: "製品・サービスの経験を、期待や理想との比較を含めて総合的に評価した満足状態。",
      domain: "サービス・顧客関係",
      relatedConcepts: ["service-quality"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1177/002224299606000403"],
    },
    {
      id: "consumer-based-brand-equity",
      nameJa: "消費者ベース・ブランド・エクイティ",
      nameEn: "Consumer-Based Brand Equity",
      definitionJa: "ブランドに関する認知、連想、品質知覚、ロイヤルティなどに基づく、個々の消費者レベルのブランド価値。",
      domain: "ブランド・消費者経験",
      relatedConcepts: ["brand-trust", "brand-personality"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1016/S0148-2963(99)00098-3"],
    },
    {
      id: "organizational-commitment",
      nameJa: "組織コミットメント",
      nameEn: "Organizational Commitment",
      definitionJa: "従業員と組織の関係を特徴づけ、組織に留まる意思決定に関係する心理状態。",
      domain: "組織行動・人的資源",
      relatedConcepts: ["organizational-identification", "job-satisfaction"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1111/j.2044-8325.1990.tb00506.x"],
    },
    {
      id: "job-satisfaction",
      nameJa: "職務満足",
      nameEn: "Job Satisfaction",
      definitionJa: "仕事全体および給与、昇進、上司、同僚、仕事の性質などの側面に対する満足評価。",
      domain: "組織行動・人的資源",
      relatedConcepts: ["organizational-commitment", "psychological-empowerment"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1007/BF00929796"],
    },
    {
      id: "psychological-empowerment",
      nameJa: "心理的エンパワーメント",
      nameEn: "Psychological Empowerment",
      definitionJa: "仕事の意味、有能感、自己決定、影響力に関する認知から構成される、職場での主体的な心理状態。",
      domain: "組織行動・人的資源",
      relatedConcepts: ["job-satisfaction", "sense-of-agency"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.5465/256865"],
    },
    {
      id: "perceived-value",
      nameJa: "知覚価値",
      nameEn: "Perceived Value",
      definitionJa: "製品やサービスから得られる便益と、支払う費用・犠牲との比較を含む消費者の総合的な価値評価。",
      domain: "サービス・顧客関係",
      relatedConcepts: ["customer-satisfaction", "service-quality"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1016/S0022-4359(01)00041-0"],
    },
    {
      id: "brand-authenticity",
      nameJa: "ブランド真正性",
      nameEn: "Brand Authenticity",
      definitionJa: "ブランドが品質への約束、誠実さ、歴史的な連続性を備え、本物らしいと消費者に知覚される程度。",
      domain: "ブランド・消費者経験",
      relatedConcepts: ["brand-trust", "brand-experience"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1016/j.jbusres.2013.06.001"],
    },
    {
      id: "consumer-ethnocentrism",
      nameJa: "消費者エスノセントリズム",
      nameEn: "Consumer Ethnocentrism",
      definitionJa: "外国製品を購入することの適切性や道徳性を、自国経済や雇用への影響から評価する消費者の傾向。",
      domain: "ブランド・消費者経験",
      relatedConcepts: ["consumer-based-brand-equity"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1177/002224378702400304"],
    },
    {
      id: "organizational-justice",
      nameJa: "組織的公正",
      nameEn: "Organizational Justice",
      definitionJa: "組織における結果の配分、意思決定手続、対人的な扱い、説明や情報提供が公正であるという知覚。",
      domain: "組織行動・人的資源",
      relatedConcepts: ["job-satisfaction", "organizational-commitment"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1037/0021-9010.86.3.386"],
    },
    {
      id: "psychological-safety",
      nameJa: "心理的安全性",
      nameEn: "Psychological Safety",
      definitionJa: "対人的なリスクを取っても安全であるという、チーム成員に共有された信念。",
      domain: "組織行動・人的資源",
      relatedConcepts: ["organizational-justice", "work-engagement"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.2307/2666999"],
    },
    {
      id: "work-engagement",
      nameJa: "ワーク・エンゲイジメント",
      nameEn: "Work Engagement",
      definitionJa: "活力、熱意、没頭によって特徴づけられる、持続的で充実した仕事関連の心理状態。",
      domain: "組織行動・人的資源",
      relatedConcepts: ["job-satisfaction", "psychological-safety", "organizational-commitment"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1177/0013164405282471"],
    },
    {
      id: "perceived-usefulness",
      nameJa: "知覚有用性",
      nameEn: "Perceived Usefulness",
      definitionJa: "特定の情報システムを使うことで、自分の仕事や課題の成果が高まると利用者が信じる程度。",
      domain: "技術受容・情報システム",
      relatedConcepts: ["perceived-ease-of-use"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.2307/249008"],
    },
    {
      id: "perceived-ease-of-use",
      nameJa: "知覚容易性",
      nameEn: "Perceived Ease of Use",
      definitionJa: "特定の情報システムを、努力をあまり必要とせず容易に使えると利用者が信じる程度。",
      domain: "技術受容・情報システム",
      relatedConcepts: ["perceived-usefulness"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.2307/249008"],
    },
    {
      id: "perceived-organizational-support",
      nameJa: "知覚組織支援",
      nameEn: "Perceived Organizational Support",
      definitionJa: "組織が自分の貢献を評価し、自分の幸福や健康を気遣っているという従業員の包括的な信念。",
      domain: "組織行動・人的資源",
      relatedConcepts: ["organizational-commitment", "organizational-justice", "work-engagement"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1037/0021-9010.71.3.500", "10.1093/joccuh/uiae034"],
    },
    {
      id: "leader-member-exchange",
      nameJa: "リーダー・メンバー交換関係",
      nameEn: "Leader–Member Exchange",
      definitionJa: "上司と部下の二者間に形成される、信頼、支援、相互義務などを含む交換関係の質。",
      domain: "組織行動・人的資源",
      relatedConcepts: ["organizational-justice", "job-satisfaction"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1016/1048-9843(95)90036-5"],
    },
    {
      id: "job-crafting",
      nameJa: "ジョブ・クラフティング",
      nameEn: "Job Crafting",
      definitionJa: "従業員が自ら仕事の資源や要求を調整し、仕事の内容や関係を主体的に作り変える行動。",
      domain: "組織行動・人的資源",
      relatedConcepts: ["work-engagement", "psychological-empowerment"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1016/j.jvb.2011.05.009"],
    },
    {
      id: "burnout",
      nameJa: "バーンアウト",
      nameEn: "Burnout",
      definitionJa: "慢性的な仕事上のストレスに関連する、消耗感、仕事への冷笑的態度、職務上の効力感低下から捉える状態。",
      domain: "組織行動・人的資源",
      relatedConcepts: ["work-engagement", "job-satisfaction"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1002/job.4030020205", "10.4992/jjpsy.75.415"],
    },
    {
      id: "consumer-innovativeness",
      nameJa: "消費者革新性",
      nameEn: "Consumer Innovativeness",
      definitionJa: "特定の製品領域で、新しい製品やアイデアを他者より早く知り、採用する消費者の傾向。",
      domain: "ブランド・消費者経験",
      relatedConcepts: ["consumer-ethnocentrism"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1177/009207039101900306"],
    },
  ],

  scales: [
    {
      id: "brand-experience-scale",
      name: "Brand Experience Scale",
      abbreviation: "BXS",
      conceptId: "brand-experience",
      authors: ["J. Joško Brakus", "Bernd H. Schmitt", "Lia Zarantonello"],
      year: 2009,
      sourceTitle: "Brand Experience: What Is It? How Is It Measured? Does It Affect Loyalty?",
      journal: "Journal of Marketing, 73(3), 52–68",
      doi: "10.1509/jmkg.73.3.52",
      itemCount: 12,
      dimensions: ["Sensory", "Affective", "Intellectual", "Behavioral"],
      responseFormat: "7件法",
      reverseItems: [], scoring: "4下位次元。得点化は原典を確認。",
      targetPopulation: ["消費者", "ブランド利用者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "unconfirmed",
      japaneseStatusNote: "Brakus尺度そのものの検証済み日本語版・日本語使用例は、今回の確認範囲では登録していません。",
      japaneseEvidence: [
        { kind: "context-reference", label: "日本的ブランド経験尺度開発に向けた概念・尺度検討", title: "「ブランド経験」概念の意義と展開", year: 2016, doi: "10.7222/marketing.2016.029", url: "https://doi.org/10.7222/marketing.2016.029" },
      ],
      validationStudies: [], usagePermission: "unknown",
      usageEvidence: [],
      itemPublicationStatus: "not-published", items: [],
      notes: "日本語での研究・予備的検討はあるが、検証済み日本語版としては未登録。",
      recordStatus: "verified-metadata",
    },
    {
      id: "brand-attachment-scale-park",
      name: "Brand Attachment Scale",
      abbreviation: "BAS",
      conceptId: "brand-attachment",
      authors: ["C. Whan Park", "Deborah J. MacInnis", "Joseph Priester", "Andreas B. Eisingerich", "Dawn Iacobucci"],
      year: 2010,
      sourceTitle: "Brand Attachment and Brand Attitude Strength: Conceptual and Empirical Differentiation of Two Critical Brand Equity Drivers",
      journal: "Journal of Marketing, 74(6), 1–17",
      doi: "10.1509/jmkg.74.6.1",
      itemCount: 4,
      dimensions: ["Brand–self connection", "Brand prominence"],
      responseFormat: "11件法（0–10）",
      reverseItems: [], scoring: "各次元2項目。得点化は原典を確認。",
      targetPopulation: ["消費者", "ブランド利用者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "unconfirmed",
      japaneseStatusNote: "Parkらの4項目版そのものの日本語版・日本語使用例は、今回の確認範囲では登録していません。",
      japaneseEvidence: [],
      validationStudies: [], usagePermission: "unknown",
      usageEvidence: [
        { kind: "systematic-review-count", count: 37, denominator: 139, label: "レビュー内で37研究が使用", scope: "2021年9月までの英語査読誌を対象としたブランド愛着レビュー。尺度を報告した139研究中。", checkedAt: "2026-07-13", title: "Brand attachment: a review and future research", year: 2022, doi: "10.1057/s41262-022-00279-5", url: "https://doi.org/10.1057/s41262-022-00279-5" },
      ],
      usageStudies: [
        { title: "How Do Different Types of Community Commitment Influence Brand Commitment? The Mediation of Brand Attachment", authors: "Zhang, Zhou, Su, & Zhou", year: 2013, context: "中国のオンライン携帯電話ブランド・コミュニティ", sample: "オンラインブランドコミュニティ参加者404名", itemCount: 4, responseFormat: "6件法", language: "Chinese", adaptation: "Parkらの4項目を中国語へ翻訳し、英中バイリンガルのマーケティング研究者12名が表現を確認。", result: "ブランド自己結合とブランド顕著性の2次元。各次元のα=.832／.864、項目負荷=.925／.938を報告。", doi: "10.1089/cyber.2012.0456", url: "https://doi.org/10.1089/cyber.2012.0456" },
        { title: "Positive and Negative Behaviours Resulting from Brand Attachment: The Moderating Effects of Attachment Styles", authors: "Japutra, Ekinci, & Simkin", year: 2018, context: "英国の消費者が選んだ愛用ブランド", sample: "英国各都市から募集した消費者432名", itemCount: 4, responseFormat: "点数は本文で明示確認できず", language: "English", adaptation: "Parkらの4項目を使用。ブランド自己結合2項目とブランド顕著性2項目で構成。", result: "項目負荷=.77～.89。測定モデルはCFI=.98、RMSEA=.04で、構成概念のCRはすべて.70超。", doi: "10.1108/EJM-10-2016-0566", url: "https://doi.org/10.1108/EJM-10-2016-0566" },
      ],
      applicationEvidence: [
        { label: "原著内で比較された版", itemCounts: [8, 4], evidenceType: "scale-development", summary: "原著は8項目版と簡潔な4項目版を比較し、最終的に4項目版を採用。後続レビューでは4項目版の使用が37研究で確認されています。", title: "Brand Attachment and Brand Attitude Strength", year: 2010, doi: "10.1509/jmkg.74.6.1", url: "https://doi.org/10.1509/jmkg.74.6.1" },
      ],
      itemPublicationStatus: "not-published", items: [],
      notes: "原著では8項目版との比較後、簡潔な4項目版を採用。",
      recordStatus: "verified-metadata",
    },
    {
      id: "sense-of-agency-scale",
      name: "Sense of Agency Scale",
      abbreviation: "SoAS",
      conceptId: "sense-of-agency",
      authors: ["Adam Tapal", "Ela Oren", "Reuven Dar", "Baruch Eitam"],
      year: 2017,
      sourceTitle: "The Sense of Agency Scale: A Measure of Consciously Perceived Control over One's Mind, Body, and the Immediate Environment",
      journal: "Frontiers in Psychology, 8, 1552",
      doi: "10.3389/fpsyg.2017.01552",
      itemCount: 13,
      dimensions: ["Sense of Positive Agency (SoPA)", "Sense of Negative Agency (SoNA)"],
      responseFormat: "5件法",
      reverseItems: [], scoring: "2下位尺度。原典の因子構造と得点化を確認。",
      targetPopulation: ["一般成人"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "validated",
      japaneseStatusNote: "J-SoASは、原版と同じ2因子・13項目について、日本の20～60代8,237名を対象に信頼性・構成概念妥当性・年齢群間の構造を検討した研究で報告されています。",
      japaneseEvidence: [
        { kind: "psychometric-validation", label: "検証済み日本語版（J-SoAS）", authors: "Xu, Legaspi, Ishikawa, & Washida", year: 2024, title: "Measuring general sense of agency: a Japanese adaptation and validation of the sense of agency scale (J-SoAS)", doi: "10.3389/fpsyg.2024.1427169", url: "https://doi.org/10.3389/fpsyg.2024.1427169" },
      ],
      validationStudies: [], usagePermission: "unknown",
      usageEvidence: [],
      itemPublicationStatus: "not-published", items: [],
      notes: "特定課題ではなく、文脈横断的・一般的な主体感の信念を測定。原著はオープンアクセス。",
      recordStatus: "verified-metadata",
    },
    {
      id: "sense-of-agency-rating-scale",
      name: "Sense of Agency Rating Scale",
      abbreviation: "SOARS",
      conceptId: "sense-of-agency",
      authors: ["Vince Polito", "Amanda J. Barnier", "Erik Z. Woody"],
      year: 2013,
      sourceTitle: "Developing the Sense of Agency Rating Scale (SOARS): An Empirical Measure of Agency Disruption in Hypnosis",
      journal: "Consciousness and Cognition, 22(3), 684–696",
      doi: "10.1016/j.concog.2013.04.003",
      itemCount: 10,
      dimensions: ["Involuntariness", "Effortlessness"],
      responseFormat: "7件法",
      reverseItems: [1, 2, 3, 5, 10], scoring: "2下位尺度、各5項目。原典を確認。",
      targetPopulation: ["催眠参加者", "特定経験後の参加者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "unconfirmed",
      japaneseStatusNote: "SOARSそのものの日本語版・日本語使用例は、今回の確認範囲では登録していません。SoASや日本独自の主体感尺度とは別尺度です。",
      japaneseEvidence: [],
      validationStudies: [], usagePermission: "unknown",
      usageEvidence: [],
      itemPublicationStatus: "not-published", items: [],
      notes: "催眠中の主体感変容を測る目的で開発。一般的な主体感尺度SoASとは用途が異なる。",
      recordStatus: "verified-metadata",
    },
    {
      id: "itc-sopi",
      name: "ITC-Sense of Presence Inventory",
      abbreviation: "ITC-SOPI",
      conceptId: "presence",
      authors: ["Jane Lessiter", "Jonathan Freeman", "Edmund Keogh", "Jules Davidoff"],
      year: 2001,
      sourceTitle: "A Cross-Media Presence Questionnaire: The ITC-Sense of Presence Inventory",
      journal: "Presence: Teleoperators & Virtual Environments, 10(3), 282–297",
      doi: "10.1162/105474601300343612",
      itemCount: 44,
      dimensions: ["Sense of Physical Space", "Engagement", "Ecological Validity", "Negative Effects"],
      responseFormat: "5件法",
      reverseItems: [], scoring: "4下位尺度。得点化は原典を確認。",
      targetPopulation: ["メディア利用者", "VR利用者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "usage-example",
      japaneseStatusNote: "日本語への翻訳・改変を用いた研究例を確認していますが、尺度全体の心理測定学的な日本語版検証は未登録です。",
      japaneseEvidence: [
        { kind: "usage-example", label: "日本語訳・改変版の使用例", title: "SCSQ-VRを用いた研究での日本語訳・改変版ITC-SOPI", year: 2025, url: "https://www.ieice.org/publications/proceedings/bin/pdf_link.php?fname=09_kamada2.pdf&iconf=KICSS&lang=E&number=9&vol=95&year=2025" },
      ],
      validationStudies: [], usagePermission: "unknown",
      usageEvidence: [
        { kind: "systematic-review-count", count: 5, label: "レビュー内で5研究が使用", scope: "人間行動を扱う仮想環境研究の系統的レビューに含まれた研究内。レビュー全体の累計利用数ではありません。", checkedAt: "2026-07-13", title: "The Use of Sense of Presence in Studies on Human Behavior in Virtual Environments: A Systematic Review", year: 2023, doi: "10.3390/app132413095", url: "https://doi.org/10.3390/app132413095" },
      ],
      itemPublicationStatus: "not-published", items: [],
      notes: "インタラクティブ・非インタラクティブ双方のメディアを横断して測定する設計。",
      recordStatus: "verified-metadata",
    },
    {
      id: "igroup-presence-questionnaire",
      name: "Igroup Presence Questionnaire",
      abbreviation: "IPQ",
      conceptId: "presence",
      authors: ["Thomas Schubert", "Frank Friedmann", "Holger Regenbrecht"],
      year: 2001,
      sourceTitle: "The Experience of Presence: Factor Analytic Insights",
      journal: "Presence: Teleoperators & Virtual Environments, 10(3), 266–281",
      doi: "10.1162/105474601300343603",
      itemCount: 14,
      dimensions: ["Spatial Presence", "Involvement", "Experienced Realism", "General Presence item"],
      responseFormat: "7段階（−3～+3）",
      reverseItems: [], scoring: "3下位尺度と一般項目。公式資料を確認。",
      targetPopulation: ["VR利用者"],
      language: "German / English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "linguistic-validated",
      japaneseStatusNote: "公式サイトの非公式訳とは別に、順翻訳・逆翻訳・専門家レビュー・認知面接・原著者確認を経た日本語版が報告されています。信頼性・構成概念妥当性の検証は今後の課題と明記されています。",
      japaneseEvidence: [
        { kind: "linguistic-validation", label: "言語的妥当性を確認した日本語版", authors: "甘利ほか", year: 2025, title: "言語的妥当性を担保した日本語版 Igroup Presence Questionnaire の作成", doi: "10.7876/jmvr.24.1", url: "https://doi.org/10.7876/jmvr.24.1" },
      ],
      validationStudies: [], usagePermission: "unknown",
      usageEvidence: [
        { kind: "systematic-review-count", count: 2, label: "レビュー内で2研究が使用", scope: "人間行動を扱う仮想環境研究の系統的レビューに含まれた研究内。別領域・別期間の利用は含みません。", checkedAt: "2026-07-13", title: "The Use of Sense of Presence in Studies on Human Behavior in Virtual Environments: A Systematic Review", year: 2023, doi: "10.3390/app132413095", url: "https://doi.org/10.3390/app132413095" },
      ],
      itemPublicationStatus: "not-published", items: [],
      notes: "公式IPQサイトで尺度情報と各言語版が案内されている。日本語版の妥当性検証は未登録。",
      recordStatus: "verified-metadata",
    },
    {
      id: "sense-of-agency-scale-asai",
      name: "Sense of Agency Scale",
      abbreviation: "SOAS（浅井ほか）",
      conceptId: "sense-of-agency",
      authors: ["Tomohisa Asai", "Keisuke Takano", "Eriko Sugimori", "Yoshihiko Tanno"],
      year: 2009,
      sourceTitle: "Development of the Sense of Agency Scale and Its Factor Structure",
      journal: "The Japanese Journal of Psychology, 80(5), 414–421",
      doi: "10.4992/jjpsy.80.414",
      itemCount: 17,
      dimensions: ["心的状態への主体帰属の誤り", "身体活動の統制欠如", "社会的活動での自己主張"],
      responseFormat: "原典を確認",
      reverseItems: [], scoring: "3因子17項目。得点化は原典を確認。",
      targetPopulation: ["日本語話者の一般成人"],
      language: "Japanese", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "original-japanese",
      japaneseStatusNote: "日本語で開発され、4回の縦断調査を通じて信頼性・妥当性が報告された主体感尺度です。TapalらのSoASとは目的・因子構造が異なります。",
      japaneseEvidence: [
        { kind: "original-japanese", label: "日本語で開発・検証された尺度", authors: "浅井・高野・杉森・丹野", year: 2009, title: "自己主体感を測定する尺度の開発と因子構造の探索", doi: "10.4992/jjpsy.80.414", url: "https://doi.org/10.4992/jjpsy.80.414" },
      ],
      validationStudies: [], usagePermission: "unknown",
      usageEvidence: [],
      itemPublicationStatus: "not-published", items: [],
      notes: "Tapalらの一般的主体感尺度（SoAS）と名称が近いが、別に開発された日本語尺度。",
      recordStatus: "verified-metadata",
    },
    {
      id: "flow-state-scale",
      name: "Flow State Scale",
      abbreviation: "FSS",
      conceptId: "flow",
      authors: ["Susan A. Jackson", "Herbert W. Marsh"],
      year: 1996,
      sourceTitle: "Development and Validation of a Scale to Measure Optimal Experience: The Flow State Scale",
      journal: "Journal of Sport & Exercise Psychology, 18(1), 17–35",
      doi: "10.1123/jsep.18.1.17",
      itemCount: 36,
      dimensions: ["Challenge–skill balance", "Action–awareness merging", "Clear goals", "Unambiguous feedback", "Concentration", "Sense of control", "Loss of self-consciousness", "Transformation of time", "Autotelic experience"],
      responseFormat: "5件法",
      reverseItems: [], scoring: "9下位尺度、各4項目。得点化は原典を確認。",
      targetPopulation: ["スポーツ・身体活動参加者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "translation-study",
      japaneseStatusNote: "原版FSSの日本語版について、因子構造を扱う日本語版の検討が報告されています。別途、改訂版FSS-2の日本語版では信頼性・因子妥当性の検証があります。",
      japaneseEvidence: [
        { kind: "translation-study", label: "原版FSSの日本語版の検討", authors: "川端・張本", year: 2000, title: "Flow State Scale（日本語版）の検討：その1", doi: "10.20693/jspeconf.51.0_183", url: "https://doi.org/10.20693/jspeconf.51.0_183" },
        { kind: "related-version", label: "改訂版FSS-2の検証済み日本語版", authors: "Kawabata, Mallett, & Jackson", year: 2008, title: "The Flow State Scale-2 and Dispositional Flow Scale-2: Examination of factorial validity and reliability for Japanese adults", doi: "10.1016/j.psychsport.2007.05.005", url: "https://doi.org/10.1016/j.psychsport.2007.05.005" },
      ],
      validationStudies: [], usagePermission: "unknown",
      usageEvidence: [
        { kind: "systematic-review-count", count: 13, denominator: 69, label: "レビュー内で13研究が使用", scope: "フローを扱う69研究のレビュー内。FSS-2ではなく原版FSSとして集計された件数。", checkedAt: "2026-07-13", title: "Measuring Flow: Refining Research Protocols That Integrate Physiological and Psychological Approaches", year: 2025, doi: "10.1155/hbe2/6464984", url: "https://doi.org/10.1155/hbe2/6464984" },
      ],
      itemPublicationStatus: "not-published", items: [],
      notes: "状態としてのフローを多次元で測る原版。",
      recordStatus: "verified-metadata",
    },
    {
      id: "short-flow-state-scale-2",
      name: "Short Flow State Scale-2",
      abbreviation: "S FSS-2",
      conceptId: "flow",
      authors: ["Susan A. Jackson", "Andrew J. Martin", "Robert C. Eklund"],
      year: 2008,
      sourceTitle: "Long and Short Measures of Flow: The Construct Validity of the FSS-2, DFS-2, and New Brief Counterparts",
      journal: "Journal of Sport & Exercise Psychology, 30(5), 561–587",
      doi: "10.1123/jsep.30.5.561",
      itemCount: 9,
      dimensions: ["9つのフロー次元を各1項目で代表"],
      responseFormat: "5件法",
      reverseItems: [], scoring: "9項目の集約的得点。原典を確認。",
      targetPopulation: ["スポーツ・身体活動参加者"],
      language: "English", versionType: "short", parentScaleId: "flow-state-scale",
      japaneseVersionStatus: "related-version",
      japaneseStatusNote: "9項目のShort FSS-2そのものの日本語版は未登録です。ただし、基礎となる長尺版FSS-2には検証済み日本語版があります。",
      japaneseEvidence: [
        { kind: "related-version", label: "長尺版FSS-2の検証済み日本語版", authors: "Kawabata, Mallett, & Jackson", year: 2008, title: "The Flow State Scale-2 and Dispositional Flow Scale-2: Examination of factorial validity and reliability for Japanese adults", doi: "10.1016/j.psychsport.2007.05.005", url: "https://doi.org/10.1016/j.psychsport.2007.05.005" },
      ],
      validationStudies: [], usagePermission: "unknown",
      usageEvidence: [],
      itemPublicationStatus: "not-published", items: [],
      notes: "36項目版を使えない場合の短縮選択肢。状態版と特性版の短縮尺度が検証された。",
      recordStatus: "verified-metadata",
    },
    {
      id: "brand-personality-scale-aaker",
      name: "Brand Personality Scale",
      abbreviation: "BPS",
      conceptId: "brand-personality",
      authors: ["Jennifer L. Aaker"],
      year: 1997,
      sourceTitle: "Dimensions of Brand Personality",
      journal: "Journal of Marketing Research, 34(3), 347–356",
      doi: "10.1177/002224379703400304",
      itemCount: 42,
      dimensions: ["Sincerity", "Excitement", "Competence", "Sophistication", "Ruggedness"],
      responseFormat: "5件法（ブランドをどの程度よく表すか）",
      reverseItems: [], scoring: "5次元。文化・文脈による因子構造の違いに注意し、原典を確認。",
      targetPopulation: ["消費者", "ブランド評価者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "related-version",
      japaneseStatusNote: "原版5次元をそのまま翻訳した版とは別に、日本と米国のブランド・パーソナリティ構造を比較し、日本固有のPeacefulness次元を報告した研究があります。",
      japaneseEvidence: [
        { kind: "related-version", label: "日本文化におけるブランド・パーソナリティ構造", authors: "Aaker, Benet-Martínez, & Garolera", year: 2001, title: "Consumption Symbols as Carriers of Culture: A Study of Japanese and Spanish Brand Personality Constructs", doi: "10.1037//0022-3514.81.3.492", url: "https://doi.org/10.1037/0022-3514.81.3.492" },
      ],
      validationStudies: [], usagePermission: "unknown",
      usageEvidence: [
        { kind: "systematic-review-count", count: 50, label: "レビュー内で50研究が使用", scope: "デジタル環境におけるブランド・パーソナリティ研究の系統的レビュー内。原版を直接または軽微な修正で使用した研究。", checkedAt: "2026-07-13", title: "Consumers’ brand personality perceptions in a digital world: A systematic literature review and research agenda", year: 2022, doi: "10.1111/ijcs.12791", url: "https://doi.org/10.1111/ijcs.12791" },
      ],
      psychometricEvidence: [
        { label: "原著の尺度開発", sample: "複数ブランド・製品カテゴリ", methods: "因子分析、信頼性・妥当性・一般化可能性の検討", result: "5次元42特性の尺度を報告", url: "https://doi.org/10.1177/002224379703400304" },
      ],
      itemPublicationStatus: "not-published", items: [],
      notes: "文化によって次元構造が変わり得るため、国際比較では文化別研究も確認する。",
      recordStatus: "verified-metadata",
    },
    {
      id: "servqual",
      name: "SERVQUAL",
      abbreviation: "SERVQUAL",
      conceptId: "service-quality",
      authors: ["A. Parasuraman", "Valarie A. Zeithaml", "Leonard L. Berry"],
      year: 1988,
      sourceTitle: "SERVQUAL: A Multiple-Item Scale for Measuring Consumer Perceptions of Service Quality",
      journal: "Journal of Retailing, 64(1), 12–40",
      doi: "",
      itemCount: 22,
      dimensions: ["Tangibles", "Reliability", "Responsiveness", "Assurance", "Empathy"],
      responseFormat: "7件法・期待と知覚を対応する22項目で測定",
      reverseItems: [], scoring: "一般に知覚得点から期待得点を差し引く。改変版が多いため原典と採用研究を確認。",
      targetPopulation: ["サービス利用者", "顧客"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "usage-example",
      japaneseStatusNote: "日本のサービス研究でSERVQUALの再検討・改変を行った実証研究があります。標準化された単一の日本語版としてではなく、研究ごとの訳・適用として扱います。",
      japaneseEvidence: [
        { kind: "usage-example", label: "日本での実証的な再検討", authors: "松尾・奥瀬・プラート", year: 2001, title: "サービス・クオリティ次元に関する実証研究―SERVQUALの再検討", doi: "10.5844/jsmd.4.29", url: "https://doi.org/10.5844/jsmd.4.29" },
        { kind: "context-reference", label: "日本語による尺度開発史の整理", authors: "山本", year: 1995, title: "サービス品質概念と品質評価尺度の開発―SERVQUALの開発とその後", doi: "10.11194/acs1993.3.41", url: "https://doi.org/10.11194/acs1993.3.41" },
      ],
      validationStudies: [], usagePermission: "unknown",
      usageEvidence: [
        { kind: "systematic-review-count", count: 60, label: "10年間のレビューで60論文を収集", scope: "SERVQUALの利用を扱った10年間のレビューが、複数誌・学会録から収集した60論文。全世界の累計利用数ではありません。", checkedAt: "2026-07-13", title: "10 Years of Service Quality Measurement: Reviewing the Use of the SERVQUAL Instrument", year: 2002, doi: "10.46631/jefas.2002.v7n13.05", url: "https://doi.org/10.46631/jefas.2002.v7n13.05" },
      ],
      psychometricEvidence: [
        { label: "原著の尺度開発", sample: "4つの独立標本", methods: "信頼性、因子構造、妥当性の検討", result: "5次元22項目の尺度を報告", url: "https://scholar.google.com/scholar?q=SERVQUAL%3A+A+Multiple-Item+Scale+for+Measuring+Consumer+Perceptions+of+Service+Quality" },
      ],
      itemPublicationStatus: "not-published", items: [],
      notes: "22項目を期待と知覚の双方で尋ねるため、回答数は通常44。業種別改変が非常に多い。",
      recordStatus: "verified-metadata",
    },
    {
      id: "markor",
      name: "MARKOR",
      abbreviation: "MARKOR",
      conceptId: "market-orientation",
      authors: ["Ajay K. Kohli", "Bernard J. Jaworski", "Ajith Kumar"],
      year: 1993,
      sourceTitle: "MARKOR: A Measure of Market Orientation",
      journal: "Journal of Marketing Research, 30(4), 467–477",
      doi: "10.1177/002224379303000406",
      itemCount: 20,
      dimensions: ["Intelligence generation", "Intelligence dissemination", "Responsiveness"],
      responseFormat: "5件法",
      reverseItems: [], scoring: "3活動を中心に構成。単一・複数回答者設計の違いを原典で確認。",
      targetPopulation: ["企業の管理者", "マーケティング・非マーケティング部門"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "unconfirmed",
      japaneseStatusNote: "日本語文献でMARKORの紹介・検討は確認していますが、原版20項目の標準化された日本語版としては未登録です。",
      japaneseEvidence: [
        { kind: "context-reference", label: "日本語によるMARKORの方法論的検討", title: "市場志向研究の方法論上の諸問題", year: 2007, url: "https://merc.e.u-tokyo.ac.jp/mmrc/dp/pdf/MMRC110_2007.pdf" },
      ],
      validationStudies: [], usagePermission: "unknown", usageEvidence: [],
      psychometricEvidence: [
        { label: "原著の尺度開発", sample: "単一回答者調査と複数回答者による追試", methods: "予備調査、因子構造、妥当性の検討", result: "20項目の市場志向尺度を報告", url: "https://doi.org/10.1177/002224379303000406" },
      ],
      applicationEvidence: [
        { label: "日本の小売従業員研究での調整版", itemCounts: [20, 12], evidenceType: "usage-study", summary: "MARKOR原版20項目に対し、日本の小売店頭従業員向け研究では文言を調整した12項目で測定し、探索的因子分析を実施。", title: "市場志向が非正規店頭従業員の行動に与える影響", year: 2015, url: "https://www.bus.nihon-u.ac.jp/wp-content/themes/nichidai/assets/img/unique/laboratory/kiyo/YokoyamaNarimasa32.pdf" },
      ],
      usageStudies: [
        { title: "Changing Roles and New Perspectives: Towards Market Orientation in Public Transport", authors: "Sofia Molander", year: 2018, context: "スウェーデンの公共交通", sample: "公共交通当局・運行事業者、2時点計184名", itemCount: 11, responseFormat: "5件法", language: "Swedish", adaptation: "MARKORを情報生成3・情報普及3・反応5項目に調整。公共交通文脈へ翻訳・文言調整。", result: "2011年と2014年の2時点で同じ11項目構成を使用。", doi: "10.1007/s11116-017-9781-3", url: "https://doi.org/10.1007/s11116-017-9781-3" },
        { title: "市場志向が非正規店頭従業員の行動に与える影響", year: 2015, context: "日本の小売店頭", sample: "非正規店頭従業員（標本詳細は本文参照）", itemCount: 12, responseFormat: "本文参照", language: "Japanese", adaptation: "MARKORを店頭従業員の文脈に合わせて12項目へ調整し、探索的因子分析を実施。", url: "https://www.bus.nihon-u.ac.jp/wp-content/themes/nichidai/assets/img/unique/laboratory/kiyo/YokoyamaNarimasa32.pdf" },
      ],
      itemPublicationStatus: "not-published", items: [],
      notes: "市場志向にはMKTORなど別系統尺度もあるため、概念定義との適合を確認する。",
      recordStatus: "verified-metadata",
    },
    {
      id: "mktor",
      name: "Market Orientation Scale",
      abbreviation: "MKTOR",
      conceptId: "market-orientation",
      authors: ["John C. Narver", "Stanley F. Slater"],
      year: 1990,
      sourceTitle: "The Effect of a Market Orientation on Business Profitability",
      journal: "Journal of Marketing, 54(4), 20–35",
      doi: "10.1177/002224299005400403",
      itemCount: 15,
      dimensions: ["Customer orientation", "Competitor orientation", "Interfunctional coordination"],
      responseFormat: "7件法",
      reverseItems: [], scoring: "顧客志向6、競争志向4、部門間調整5項目。3次元の平均から市場志向を捉える。",
      targetPopulation: ["企業の管理者", "事業単位責任者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "usage-example",
      japaneseStatusNote: "日本語の市場志向研究でMKTORの全部または一部を援用した使用例がありますが、統一された標準日本語版としては未登録です。",
      japaneseEvidence: [
        { kind: "usage-example", label: "日本語研究でのMKTOR援用例", year: 2012, title: "市場志向が創造的ビジネス行動とパフォーマンスに及ぼす影響", url: "https://www.waseda.jp/fcom/soc/assets/uploads/2015/01/wcom433_03.pdf" },
      ],
      validationStudies: [], usagePermission: "unknown", usageEvidence: [],
      psychometricEvidence: [
        { label: "原著の尺度開発・適用", sample: "140事業単位", methods: "信頼性、因子構造、市場志向と収益性の関係の検討", result: "顧客志向・競争志向・部門間調整の3次元15項目を報告", url: "https://doi.org/10.1177/002224299005400403" },
      ],
      applicationEvidence: [
        { label: "MARKORとは異なる主要測定系統", itemCounts: [15], evidenceType: "scale-development", summary: "市場志向の主要尺度は、行動プロセスを測るMARKOR 20項目と、組織文化的側面を測るMKTOR 15項目に大別されます。項目数だけでなく概念定義で選ぶ必要があります。", title: "The Effect of a Market Orientation on Business Profitability", year: 1990, doi: "10.1177/002224299005400403", url: "https://doi.org/10.1177/002224299005400403" },
        { label: "オーストラリアでの8項目精選版", itemCounts: [14, 8], evidenceType: "comparative-validation", summary: "オーストラリアの民間企業標本で項目を精選し、上場企業標本で交差検証した結果、3次元8項目モデルの適合と各信頼性係数.80超を報告。原版15項目から一意に定まる公式短縮版ではなく、比較検証による精選版です。", title: "An Analysis of the MKTOR and MARKOR Measures of Market Orientation: An Australian Perspective", year: 1997, url: "https://marketing-bulletin.massey.ac.nz/V8/MB_V8_A3_Farrell.pdf" },
        { label: "セルビア輸出企業での11項目精選版", itemCounts: [15, 11], evidenceType: "comparative-validation", summary: "原版15項目と精選11項目を1因子・3因子モデルで比較し、3因子11項目モデルが最良適合。原版では弁別妥当性の問題が示されました。", title: "Testing MKTOR Scale Properties in Serbian Exporters’ Context", year: 2020, doi: "10.7595/management.fon.2019.0011", url: "https://doi.org/10.7595/management.fon.2019.0011" },
      ],
      usageStudies: [
        { title: "An Analysis of the MKTOR and MARKOR Measures of Market Orientation: An Australian Perspective", authors: "Farrell & Oczkowski", year: 1997, context: "オーストラリア企業での比較検証", sample: "民間企業190社、上場企業237社（有効回答計427社）", itemCount: 8, responseFormat: "原論文参照", language: "English", adaptation: "研究内で用いた14項目構成から6項目を削除し、3次元8項目モデルを別標本で交差検証。", result: "民間企業標本と上場企業標本で適合改善。各信頼性係数は.80超。", url: "https://marketing-bulletin.massey.ac.nz/V8/MB_V8_A3_Farrell.pdf" },
        { title: "Testing MKTOR Scale Properties in Serbian Exporters’ Context", authors: "Njegić, Đokić, & Milanović", year: 2020, context: "セルビアの輸出企業", sample: "輸出企業の管理者60名", itemCount: 11, responseFormat: "5件法", language: "Serbian", adaptation: "原版15項目を翻訳・使用した後、交差負荷などを基に4項目を除いた3次元11項目版を比較。", result: "3因子11項目モデルが比較4モデル中で最良適合。原版の弁別妥当性問題を改善。", doi: "10.7595/management.fon.2019.0011", url: "https://doi.org/10.7595/management.fon.2019.0011" },
      ],
      itemPublicationStatus: "not-published", items: [], verifiedAt: "2026-07-13",
      notes: "『3項目』ではなく、3次元15項目の原版。3つの下位次元を3つの観測指標として扱うモデルと、質問票が3項目であることは別です。後続研究には8項目・11項目の精選例があります。",
      recordStatus: "verified-metadata",
    },
    {
      id: "mortn-market-orientation-scale",
      name: "Synthesized Market Orientation Scale",
      abbreviation: "MORTN",
      conceptId: "market-orientation",
      authors: ["Rohit Deshpandé", "John U. Farley"],
      year: 1998,
      sourceTitle: "Measuring Market Orientation: Generalization and Synthesis",
      journal: "Journal of Market-Focused Management, 2, 213–232",
      doi: "10.1023/A:1009719615327",
      itemCount: 10,
      dimensions: ["Customer focus", "Continuous needs assessment"],
      responseFormat: "原典参照（後続研究では5件法の例あり）",
      reverseItems: [], scoring: "10項目を用いて、顧客創造・顧客満足に向けた部門横断的な活動を測定。研究文脈での因子構造を確認する。",
      targetPopulation: ["企業の管理者", "従業員"],
      language: "English", versionType: "short", parentScaleId: null,
      japaneseVersionStatus: "unconfirmed",
      japaneseStatusNote: "標準化された日本語版と日本語での検証研究は今回未登録です。独自翻訳で使用する場合は翻訳過程と因子構造を確認してください。",
      japaneseEvidence: [],
      validationStudies: [], usagePermission: "unknown", usageEvidence: [],
      psychometricEvidence: [
        { label: "3尺度の統合・国際比較による開発", sample: "欧米27社の管理者82名", methods: "既存3尺度の統合、信頼性・妥当性、業績との関連を比較", result: "既存尺度の国際的一般化を確認し、簡潔な10項目尺度を合成", url: "https://doi.org/10.1023/A:1009719615327" },
      ],
      applicationEvidence: [
        { label: "市場志向3尺度から合成された10項目版", itemCounts: [10, 15, 20], evidenceType: "comparative-validation", summary: "MKTOR、MARKOR、顧客志向尺度を統合して10項目へ簡潔化。顧客の表明されたニーズへの反応を中心に捉えるため、競争志向や潜在ニーズまで含めたい研究では概念範囲を確認する必要があります。", title: "Measuring Market Orientation: Generalization and Synthesis", year: 1998, doi: "10.1023/A:1009719615327", url: "https://doi.org/10.1023/A:1009719615327" },
      ],
      usageStudies: [
        { title: "Gaining a Better Understanding of the Types of Organizational Culture to Manage Suffering at Work", authors: "Assens-Serra et al.", year: 2021, context: "スペイン・ペルーの組織文化研究", sample: "スペインの管理者362名、ペルーの管理者1,317名", itemCount: 10, responseFormat: "5件法", language: "Spanish", adaptation: "表明された顧客ニーズを発見・充足する組織能力としてMORTNを使用。", result: "MORTNの信頼性α=.88を報告し、複数の組織文化との関連を検討。", doi: "10.3389/fpsyg.2021.782488", url: "https://doi.org/10.3389/fpsyg.2021.782488" },
      ],
      itemPublicationStatus: "not-published", items: [], verifiedAt: "2026-07-13",
      notes: "15項目MKTORや20項目MARKORより短い選択肢。ただし概念範囲は顧客焦点・表明ニーズへの反応に寄るため、競争志向や潜在ニーズを測る研究では別尺度も比較する。",
      recordStatus: "verified-metadata",
    },
    {
      id: "mael-ashforth-organizational-identification",
      name: "Mael–Ashforth Organizational Identification Scale",
      abbreviation: "Mael OI Scale",
      conceptId: "organizational-identification",
      authors: ["Fred Mael", "Blake E. Ashforth"],
      year: 1992,
      sourceTitle: "Alumni and Their Alma Mater: A Partial Test of the Reformulated Model of Organizational Identification",
      journal: "Journal of Organizational Behavior, 13(2), 103–123",
      doi: "10.1002/job.4030130202",
      itemCount: 6,
      dimensions: ["Organizational identification（単一次元）"],
      responseFormat: "件法は採用研究により異なるため原典・使用研究を確認",
      reverseItems: [], scoring: "6項目を集約。高得点ほど組織同一視が強い。",
      targetPopulation: ["組織成員", "卒業生"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "translation-study",
      japaneseStatusNote: "Mael尺度の構成・項目内容を日本語で検討した文献がありますが、統一された日本語版の心理測定学的検証としては未登録です。",
      japaneseEvidence: [
        { kind: "translation-study", label: "Mael尺度を扱う日本語の尺度検討", authors: "梶原・劉", year: 2015, title: "Mael尺度を考える―経営学輪講 Mael and Ashforth (1992)", url: "https://www.jstage.jst.go.jp/article/amr/14/9/14_140903/_article/-char/ja" },
      ],
      validationStudies: [], usagePermission: "unknown", usageEvidence: [],
      psychometricEvidence: [
        { label: "原著でのモデル検証", sample: "男子宗教系大学の卒業生297名", methods: "組織的・個人的先行要因と行動的結果との関連を検討", result: "6項目尺度を用いた組織同一視モデルを検証", url: "https://doi.org/10.1002/job.4030130202" },
      ],
      itemPublicationStatus: "not-published", items: [],
      notes: "組織コミットメントや情緒的愛着とは概念範囲が異なる。",
      recordStatus: "verified-metadata",
    },
    {
      id: "covin-slevin-entrepreneurial-orientation",
      name: "Covin–Slevin Entrepreneurial Orientation Scale",
      abbreviation: "EO Scale",
      conceptId: "entrepreneurial-orientation",
      authors: ["Jeffrey G. Covin", "Dennis P. Slevin"],
      year: 1989,
      sourceTitle: "Strategic Management of Small Firms in Hostile and Benign Environments",
      journal: "Strategic Management Journal, 10(1), 75–87",
      doi: "10.1002/smj.4250100107",
      itemCount: 9,
      dimensions: ["Innovativeness", "Proactiveness", "Risk-taking"],
      responseFormat: "7段階の両極尺度",
      reverseItems: [], scoring: "3次元9項目。単一次元集約か多次元扱いかは研究目的に合わせて確認。",
      targetPopulation: ["企業経営者", "中小企業管理者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "unconfirmed",
      japaneseStatusNote: "日本語での使用研究は想定されますが、原版9項目の翻訳・検証根拠を今回の登録範囲では確認していません。",
      japaneseEvidence: [],
      validationStudies: [], usagePermission: "unknown", usageEvidence: [],
      psychometricEvidence: [
        { label: "原著での適用", sample: "小規模製造企業161社", methods: "環境、構造、戦略姿勢、競争戦術、業績との関連を検討", result: "起業家的戦略姿勢と環境適合を検証", url: "https://doi.org/10.1002/smj.4250100107" },
      ],
      itemPublicationStatus: "not-published", items: [],
      notes: "Miller/Covin–Slevin系の9項目尺度。Lumpkin–Dessの5次元概念化とは区別する。",
      recordStatus: "verified-metadata",
    },
    {
      id: "consumer-brand-engagement-scale",
      name: "Consumer Brand Engagement Scale",
      abbreviation: "CBE Scale",
      conceptId: "consumer-brand-engagement",
      authors: ["Linda D. Hollebeek", "Mark S. Glynn", "Roderick J. Brodie"],
      year: 2014,
      sourceTitle: "Consumer Brand Engagement in Social Media: Conceptualization, Scale Development and Validation",
      journal: "Journal of Interactive Marketing, 28(2), 149–165",
      doi: "10.1016/j.intmar.2013.12.002",
      itemCount: 10,
      dimensions: ["Cognitive processing", "Affection", "Activation"],
      responseFormat: "7件法",
      reverseItems: [], scoring: "3次元10項目。ソーシャルメディア文脈で開発された点に注意。",
      targetPopulation: ["消費者", "ソーシャルメディア上のブランド利用者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "unconfirmed",
      japaneseStatusNote: "日本語での使用研究・翻訳例は今後の確認対象です。標準化された日本語版としては未登録です。",
      japaneseEvidence: [],
      validationStudies: [], usagePermission: "unknown", usageEvidence: [],
      psychometricEvidence: [
        { label: "原著の尺度開発", sample: "3つのソーシャルメディア文脈", methods: "探索的・確認的因子分析、競合モデル、法則的ネットワークの検証", result: "3次元10項目の尺度を報告", url: "https://doi.org/10.1016/j.intmar.2013.12.002" },
      ],
      itemPublicationStatus: "not-published", items: [],
      notes: "一般的な顧客エンゲージメント尺度とは対象・文脈が異なる。",
      recordStatus: "verified-metadata",
    },
    {
      id: "brand-trust-scale-delgado-ballester",
      name: "Brand Trust Scale",
      abbreviation: "BTS",
      conceptId: "brand-trust",
      authors: ["Elena Delgado-Ballester", "José Luis Munuera-Alemán", "María Jesús Yagüe-Guillén"],
      year: 2003,
      sourceTitle: "Development and Validation of a Brand Trust Scale",
      journal: "International Journal of Market Research, 45(1), 35–53",
      doi: "10.1177/147078530304500103",
      itemCount: 8,
      dimensions: ["Brand reliability", "Brand intentions"],
      responseFormat: "7件法",
      reverseItems: [], scoring: "2次元8項目。得点化は原典を確認。",
      targetPopulation: ["消費者", "ブランド利用者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "unconfirmed",
      japaneseStatusNote: "日本語での使用研究は今後の確認対象です。標準化された日本語版としては未登録です。",
      japaneseEvidence: [],
      validationStudies: [], usagePermission: "unknown", usageEvidence: [],
      psychometricEvidence: [
        { label: "原著の尺度開発", sample: "消費者を対象とした多段階研究", methods: "項目精選、多次元構造、信頼性・妥当性の心理測定検査", result: "Brand reliabilityとBrand intentionsからなる尺度を報告", url: "https://doi.org/10.1177/147078530304500103" },
      ],
      itemPublicationStatus: "not-published", items: [],
      notes: "一般的な対人信頼尺度ではなく、消費者―ブランド関係に特化した尺度。",
      recordStatus: "verified-metadata",
    },
    {
      id: "acsi-customer-satisfaction",
      name: "American Customer Satisfaction Index Satisfaction Measure",
      abbreviation: "ACSI Satisfaction",
      conceptId: "customer-satisfaction",
      authors: ["Claes Fornell", "Michael D. Johnson", "Eugene W. Anderson", "Jaesung Cha", "Barbara Everitt Bryant"],
      year: 1996,
      sourceTitle: "The American Customer Satisfaction Index: Nature, Purpose, and Findings",
      journal: "Journal of Marketing, 60(4), 7–18",
      doi: "10.1177/002224299606000403",
      itemCount: 3,
      dimensions: ["Overall satisfaction", "Expectation confirmation", "Comparison with ideal"],
      responseFormat: "10段階",
      reverseItems: [], scoring: "3観測変数から潜在的な顧客満足指数を推定。ACSIのモデル・重みを確認。",
      targetPopulation: ["顧客", "製品・サービス利用者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "related-version",
      japaneseStatusNote: "日本ではACSIを基礎にした日本版顧客満足度指数JCSIがありますが、構成概念やモデルを調整した関連モデルであり、ACSIの単純な日本語訳とは区別します。",
      japaneseEvidence: [
        { kind: "related-version", label: "ACSIを基礎に開発された日本版JCSI", title: "JCSI因果モデルとは", url: "https://www.jpc-net.jp/research/jcsi/causal_model/" },
        { kind: "related-version", label: "JCSIモデルの日本語開発論文", authors: "南 知惠子・小川 孔輔", year: 2010, title: "日本版顧客満足度指数（JCSI）のモデル開発とその理論的な基礎", doi: "10.7222/marketing.2010.027", url: "https://doi.org/10.7222/marketing.2010.027" },
      ],
      validationStudies: [], usagePermission: "unknown", usageEvidence: [],
      psychometricEvidence: [
        { label: "国家レベル指数モデル", sample: "米国の主要7経済部門", methods: "全国調査、計量経済モデル、部門横断・時系列ベンチマーキング", result: "企業・産業・部門・国家レベルの顧客満足指数を提示", url: "https://doi.org/10.1177/002224299606000403" },
      ],
      applicationEvidence: [
        { label: "市民満足向け3項目尺度の比較検証", itemCounts: [1, 3], evidenceType: "comparative-validation", summary: "都市サービスへの総合満足について単一項目と複数項目を比較し、ACSIに類似した簡潔な3項目尺度が信頼性・妥当性・実用性のバランスに優れると報告。ACSIそのものではなく公共サービス向け応用版です。", title: "The Measurement of Overall Citizen Satisfaction", year: 2004, doi: "10.1080/15309576.2004.11051805", url: "https://doi.org/10.1080/15309576.2004.11051805" },
        { label: "日本版JCSIの関連3項目指標", itemCounts: [3], evidenceType: "related-version", summary: "JCSIでは顧客満足を3問で構成します。ACSIを基礎とする日本向け関連モデルであり、ACSIの単純翻訳版とは区別します。", title: "日本版顧客満足度指数（JCSI）のモデル開発とその理論的な基礎", year: 2010, doi: "10.7222/marketing.2010.027", url: "https://doi.org/10.7222/marketing.2010.027" },
      ],
      usageStudies: [
        { title: "Drivers and Consequences of Citizen Satisfaction: An Application of the American Customer Satisfaction Index Model to New York City", authors: "Van Ryzin et al.", year: 2004, context: "ニューヨーク市の公共サービス", sample: "2000年・2001年の住民電話調査、計1,504名", itemCount: 3, responseFormat: "ACSI方式", language: "English", adaptation: "ACSIモデルを地方政府サービスに適用し、総合満足を3指標で測定。", result: "学校、警察、道路、地下鉄などの知覚品質と市民満足の関係を検討。", doi: "10.1111/j.1540-6210.2004.00377.x", url: "https://doi.org/10.1111/j.1540-6210.2004.00377.x" },
      ],
      itemPublicationStatus: "not-published", items: [],
      notes: "一般的な3項目満足尺度としてではなく、ACSI因果モデルの一部として利用する。",
      recordStatus: "verified-metadata",
    },
    {
      id: "multidimensional-brand-equity-scale",
      name: "Multidimensional Consumer-Based Brand Equity Scale",
      abbreviation: "MBE Scale",
      conceptId: "consumer-based-brand-equity",
      authors: ["Boonghee Yoo", "Naveen Donthu"],
      year: 2001,
      sourceTitle: "Developing and Validating a Multidimensional Consumer-Based Brand Equity Scale",
      journal: "Journal of Business Research, 52(1), 1–14",
      doi: "10.1016/S0148-2963(99)00098-3",
      itemCount: 10,
      dimensions: ["Brand loyalty", "Perceived quality", "Brand awareness / associations"],
      responseFormat: "5件法",
      reverseItems: [], scoring: "3次元10項目。多次元得点と総合指標の扱いは原典を確認。",
      targetPopulation: ["消費者", "ブランド評価者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "unconfirmed",
      japaneseStatusNote: "原版10項目の日本語版・日本語使用例は今回の確認範囲では未登録です。",
      japaneseEvidence: [],
      validationStudies: [], usagePermission: "unknown", usageEvidence: [],
      psychometricEvidence: [
        { label: "多国間の尺度開発", sample: "複数文化・複数ブランドの消費者標本", methods: "多母集団分析、因子構造、交差文化的不変性、複合信頼性", result: "3次元10項目、複合信頼性 .82–.88を報告", url: "https://doi.org/10.1016/S0148-2963(99)00098-3" },
      ],
      itemPublicationStatus: "not-published", items: [],
      notes: "企業財務ベースのブランド価値ではなく、個人消費者レベルの認知・行動を測る。",
      recordStatus: "verified-metadata",
    },
    {
      id: "three-component-organizational-commitment-scale",
      name: "Three-Component Organizational Commitment Scale",
      abbreviation: "TCM Commitment Scale",
      conceptId: "organizational-commitment",
      authors: ["Natalie J. Allen", "John P. Meyer"],
      year: 1990,
      sourceTitle: "The Measurement and Antecedents of Affective, Continuance and Normative Commitment to the Organization",
      journal: "Journal of Occupational Psychology, 63(1), 1–18",
      doi: "10.1111/j.2044-8325.1990.tb00506.x",
      itemCount: 24,
      dimensions: ["Affective commitment", "Continuance commitment", "Normative commitment"],
      responseFormat: "7件法",
      reverseItems: [], scoring: "3下位尺度、各8項目の原版。後年の18項目改訂版と区別する。",
      targetPopulation: ["従業員", "組織成員"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "validated",
      japaneseStatusNote: "Allen–Meyerの3次元尺度に基づき、日本人労働者292名で次元性・信頼性・項目特性を検討した研究があります。18項目改訂版の日本語版研究も存在します。",
      japaneseEvidence: [
        { kind: "psychometric-validation", label: "日本人労働者での次元性・信頼性・項目特性の検討", authors: "高橋", year: 1997, title: "組織コミットメント尺度の項目特性とその応用―Allen & Meyerの3次元コミットメント尺度に基づいて", doi: "10.5651/jaas.11.123", url: "https://doi.org/10.5651/jaas.11.123" },
        { kind: "related-version", label: "18項目改訂版の日本語版IRT研究", authors: "Watanabe & Takahashi", year: 2019, title: "Development of Allen and Meyer Commitment Scale Japanese Version: Based on Item Response Theory", url: "https://cir.nii.ac.jp/crid/1050282677542255872" },
      ],
      validationStudies: [], usagePermission: "permission-required", usageEvidence: [],
      psychometricEvidence: [
        { label: "原著の3成分モデル検証", sample: "組織成員を対象とする尺度開発研究", methods: "3成分の弁別性、相関要因、信頼性の検討", result: "情緒的・継続的・規範的コミットメントを区別", url: "https://doi.org/10.1111/j.2044-8325.1990.tb00506.x" },
      ],
      itemPublicationStatus: "not-published", items: [],
      notes: "著作権・利用許諾条件を確認する。1990年原版と後年の改訂版で項目数が異なる。",
      recordStatus: "verified-metadata",
    },
    {
      id: "job-satisfaction-survey",
      name: "Job Satisfaction Survey",
      abbreviation: "JSS",
      conceptId: "job-satisfaction",
      authors: ["Paul E. Spector"],
      year: 1985,
      sourceTitle: "Measurement of Human Service Staff Satisfaction: Development of the Job Satisfaction Survey",
      journal: "American Journal of Community Psychology, 13(6), 693–713",
      doi: "10.1007/BF00929796",
      itemCount: 36,
      dimensions: ["Pay", "Promotion", "Supervision", "Fringe benefits", "Contingent rewards", "Operating procedures", "Coworkers", "Nature of work", "Communication"],
      responseFormat: "6件法",
      reverseItems: [], scoring: "9下位尺度、各4項目。逆転項目と総合得点は公式資料を確認。",
      targetPopulation: ["従業員", "ヒューマンサービス・公共・非営利組織職員"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "unconfirmed",
      japaneseStatusNote: "Spectorの36項目JSSそのものの検証済み日本語版は未登録です。名称が同じ医師職務満足尺度など別尺度と混同しないでください。",
      japaneseEvidence: [],
      validationStudies: [], usagePermission: "research-use", usageEvidence: [],
      psychometricEvidence: [
        { label: "原著の尺度開発", sample: "ヒューマンサービス・公共・非営利組織の職員", methods: "項目分析、信頼性・妥当性、因子分析、JDIとの多特性多方法分析、規準値", result: "9下位尺度36項目を報告", url: "https://doi.org/10.1007/BF00929796" },
      ],
      itemPublicationStatus: "not-published", items: [],
      notes: "研究利用条件と最新版の公式配布資料は開発者サイトで確認する。",
      recordStatus: "verified-metadata",
    },
    {
      id: "spreitzer-psychological-empowerment-scale",
      name: "Psychological Empowerment Scale",
      abbreviation: "PES / PEQ",
      conceptId: "psychological-empowerment",
      authors: ["Gretchen M. Spreitzer"],
      year: 1995,
      sourceTitle: "Psychological Empowerment in the Workplace: Dimensions, Measurement, and Validation",
      journal: "Academy of Management Journal, 38(5), 1442–1465",
      doi: "10.5465/256865",
      itemCount: 12,
      dimensions: ["Meaning", "Competence", "Self-determination", "Impact"],
      responseFormat: "7件法",
      reverseItems: [], scoring: "4下位尺度、各3項目。総合得点と下位尺度得点を目的に応じて使用。",
      targetPopulation: ["従業員", "職場の組織成員"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "validated",
      japaneseStatusNote: "看護職865名を分析し、内的整合性、構造的妥当性、収束的妥当性を検討した日本語版があります。原版どおりの4因子構造を基本に修正モデルが検討されています。",
      japaneseEvidence: [
        { kind: "psychometric-validation", label: "検証済み日本語版", authors: "渡辺・金井Pak", year: 2019, title: "日本語版精神的エンパワメント尺度の信頼性・妥当性の検証", doi: "10.19012/janap.23.1_50", url: "https://doi.org/10.19012/janap.23.1_50" },
      ],
      validationStudies: [], usagePermission: "unknown", usageEvidence: [],
      psychometricEvidence: [
        { label: "原著の尺度開発", sample: "相補的な2標本", methods: "二次確認的因子分析、収束・弁別妥当性、構造方程式による法則的ネットワーク", result: "4次元12項目の構成概念妥当性を支持", url: "https://doi.org/10.5465/256865" },
        { label: "日本語版の検証", sample: "7病院・3介護老人保健施設の看護職865名", methods: "内的整合性、探索的・確認的因子分析、収束的妥当性", result: "α=.82–.90、修正4因子モデル RMSEA=.08、CFI=.96、TLI=.94", url: "https://doi.org/10.19012/janap.23.1_50" },
      ],
      itemPublicationStatus: "not-published", items: [],
      notes: "患者エンパワーメントなど別概念のPESとは区別する。日本語版の利用には開発者条件を確認。",
      recordStatus: "verified-metadata",
    },
    {
      id: "perval",
      name: "Consumer Perceived Value Scale",
      abbreviation: "PERVAL",
      conceptId: "perceived-value",
      authors: ["Jillian C. Sweeney", "Geoffrey N. Soutar"],
      year: 2001,
      sourceTitle: "Consumer Perceived Value: The Development of a Multiple Item Scale",
      journal: "Journal of Retailing, 77(2), 203–220",
      doi: "10.1016/S0022-4359(01)00041-0",
      itemCount: 19,
      dimensions: ["Emotional value", "Social value", "Quality/performance", "Price/value for money"],
      responseFormat: "7件法",
      reverseItems: [], scoring: "4下位次元。得点化は原典を確認。",
      targetPopulation: ["消費者", "耐久消費財の購入検討者・購入者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "unconfirmed",
      japaneseStatusNote: "PERVALそのものの検証済み日本語版・日本語使用例は、今回の確認範囲では登録していません。日本語研究で独自翻訳されている可能性とは区別しています。",
      japaneseEvidence: [],
      validationStudies: [], usagePermission: "unknown", usageEvidence: [],
      psychometricEvidence: [
        { label: "原著の尺度開発", sample: "耐久消費財をブランド水準で評価する購入前・購入後の消費者標本", methods: "探索的・確認的分析、購入前後での信頼性・妥当性検討", result: "4次元19項目の信頼性・妥当性を支持", url: "https://doi.org/10.1016/S0022-4359(01)00041-0" },
      ],
      itemPublicationStatus: "not-published", items: [],
      notes: "サービス向けに開発された別の知覚価値尺度や短縮・改変版と区別する。",
      recordStatus: "verified-metadata",
    },
    {
      id: "consumer-based-brand-authenticity-scale",
      name: "Consumer-Based Brand Authenticity Scale",
      abbreviation: "CBBA Scale",
      conceptId: "brand-authenticity",
      authors: ["Julie Napoli", "Sonia J. Dickinson", "Michael B. Beverland", "Francis Farrelly"],
      year: 2014,
      sourceTitle: "Measuring Consumer-Based Brand Authenticity",
      journal: "Journal of Business Research, 67(6), 1090–1098",
      doi: "10.1016/j.jbusres.2013.06.001",
      itemCount: 14,
      dimensions: ["Quality commitment", "Sincerity", "Heritage"],
      responseFormat: "原典を確認",
      reverseItems: [], scoring: "3つの一次因子と上位のブランド真正性因子。",
      targetPopulation: ["消費者", "ブランド利用者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "unconfirmed",
      japaneseStatusNote: "Napoliらの14項目版そのものの検証済み日本語版・日本語使用例は、今回の確認範囲では登録していません。Morhartらの15項目・4次元尺度とは別尺度です。",
      japaneseEvidence: [],
      validationStudies: [], usagePermission: "permission-required", usageEvidence: [],
      psychometricEvidence: [
        { label: "原著の尺度開発", sample: "4つの研究による消費者標本", methods: "尺度精製、因子構造、収束・弁別・予測妥当性の検討", result: "3次元14項目と上位因子を支持", url: "https://doi.org/10.1016/j.jbusres.2013.06.001" },
      ],
      itemPublicationStatus: "not-published", items: [],
      notes: "著者機関の公開記録ではAll rights reserved・書面許可必要とされるため、項目本文は掲載しない。",
      recordStatus: "verified-metadata",
    },
    {
      id: "cetscale",
      name: "Consumer Ethnocentric Tendencies Scale",
      abbreviation: "CETSCALE",
      conceptId: "consumer-ethnocentrism",
      authors: ["Terence A. Shimp", "Subhash Sharma"],
      year: 1987,
      sourceTitle: "Consumer Ethnocentrism: Construction and Validation of the CETSCALE",
      journal: "Journal of Marketing Research, 24(3), 280–289",
      doi: "10.1177/002224378702400304",
      itemCount: 17,
      dimensions: ["Consumer ethnocentrism"],
      responseFormat: "7件法",
      reverseItems: [], scoring: "単一次元17項目。短縮版と区別する。",
      targetPopulation: ["消費者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "unconfirmed",
      japaneseStatusNote: "CETSCALEの日本語使用研究は存在し得ますが、翻訳手続や心理測定学的検証を確認できる根拠を今回まだ登録していません。",
      japaneseEvidence: [],
      validationStudies: [], usagePermission: "unknown", usageEvidence: [],
      psychometricEvidence: [
        { label: "原著の尺度開発", sample: "米国で実施した4つの研究", methods: "信頼性、収束・弁別妥当性、法則的妥当性の検討", result: "17項目尺度の信頼性と複数の妥当性証拠を報告", url: "https://doi.org/10.1177/002224378702400304" },
      ],
      itemPublicationStatus: "not-published", items: [],
      notes: "6項目・10項目などの短縮版、各国語版とは項目数と検証根拠を分けて扱う。",
      recordStatus: "verified-metadata",
    },
    {
      id: "colquitt-organizational-justice-scale",
      name: "Organizational Justice Scale",
      abbreviation: "Colquitt OJ Scale",
      conceptId: "organizational-justice",
      authors: ["Jason A. Colquitt"],
      year: 2001,
      sourceTitle: "On the Dimensionality of Organizational Justice: A Construct Validation of a Measure",
      journal: "Journal of Applied Psychology, 86(3), 386–400",
      doi: "10.1037/0021-9010.86.3.386",
      itemCount: 20,
      dimensions: ["Procedural justice", "Distributive justice", "Interpersonal justice", "Informational justice"],
      responseFormat: "5件法",
      reverseItems: [], scoring: "手続7、分配4、対人4、情報5項目。文脈に合わせて設問導入部を設定する。",
      targetPopulation: ["従業員", "組織成員"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "related-version",
      japaneseStatusNote: "組織的公正には検証済み日本語尺度がありますが、これはMoorman尺度を修正したOJQであり、Colquittの20項目・4次元尺度とは別尺度です。Colquitt尺度そのものの日本語版は今回未登録です。",
      japaneseEvidence: [
        { kind: "related-version", label: "別尺度OJQの検証済み日本語版", authors: "Inoue et al.", year: 2009, title: "Reliability and Validity of the Japanese Version of the Organizational Justice Questionnaire", doi: "10.1539/joh.L8042", url: "https://doi.org/10.1539/joh.L8042" },
      ],
      validationStudies: [], usagePermission: "unknown", usageEvidence: [],
      psychometricEvidence: [
        { label: "原著の構成概念検証", sample: "大学生と従業員を含む複数標本", methods: "確認的因子分析、関連概念・成果との関係による妥当性検討", result: "手続・分配・対人・情報の4次元20項目を支持", url: "https://doi.org/10.1037/0021-9010.86.3.386" },
      ],
      itemPublicationStatus: "not-published", items: [],
      notes: "関連する日本語尺度の存在は示すが、Colquitt尺度の検証済み日本語版とは表示しない。",
      recordStatus: "verified-metadata",
    },
    {
      id: "edmondson-team-psychological-safety-scale",
      name: "Team Psychological Safety Scale",
      abbreviation: "TPS",
      conceptId: "psychological-safety",
      authors: ["Amy C. Edmondson"],
      year: 1999,
      sourceTitle: "Psychological Safety and Learning Behavior in Work Teams",
      journal: "Administrative Science Quarterly, 44(2), 350–383",
      doi: "10.2307/2666999",
      itemCount: 7,
      dimensions: ["Team psychological safety"],
      responseFormat: "7件法",
      reverseItems: [], scoring: "単一次元。逆転項目と集団水準への集約は原典・日本語版論文を確認。",
      targetPopulation: ["従業員", "職場チームの成員"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "validated",
      japaneseStatusNote: "国際的ガイドラインに沿って翻訳され、日本人労働者を対象に内的整合性、再検査信頼性、因子構造、関連尺度との相関を検討した日本語版があります。",
      japaneseEvidence: [
        { kind: "psychometric-validation", label: "検証済み日本語版", authors: "Ochiai & Otsuka", year: 2022, title: "Reliability and validity of the Japanese version of the psychological safety scale for workers", doi: "10.2486/indhealth.2021-0130", url: "https://doi.org/10.2486/indhealth.2021-0130" },
      ],
      validationStudies: [], usagePermission: "unknown", usageEvidence: [],
      usageStudies: [
        { title: "Psychological Safety in Intensive Care Unit Rounding Teams", authors: "Diabes et al.", year: 2021, context: "米国の集中治療室における多職種回診チーム", sample: "6病院12 ICUの医療従事者270名、延べ553回答", itemCount: 4, responseFormat: "5件法", language: "English", adaptation: "先行尺度の項目をICUの日次チーム文脈へ調整。心理的安全性の不良2項目を除外し、最終4項目で分析。", result: "α=.69。リーダーの包摂性、低い職務負担、チームワーク知覚との関連を報告。", doi: "10.1513/AnnalsATS.202006-753OC", url: "https://doi.org/10.1513/AnnalsATS.202006-753OC" },
        { title: "The Relationship between Psychological Safety and Management Team Effectiveness: The Mediating Role of Behavioral Integration", authors: "Mogård, Rørstad, & Bang", year: 2023, context: "ノルウェーの経営チーム", sample: "160経営チームのリーダー1,150名", itemCount: 4, responseFormat: "7件法", language: "本文で明示確認できず（ノルウェー調査）", adaptation: "Edmondsonらを基礎にした5項目から、行動統合との交差負荷を示した1項目を除外。", result: "α=.90。心理的安全性とチーム有効性の関係を行動統合が媒介。", doi: "10.3390/ijerph20010406", url: "https://doi.org/10.3390/ijerph20010406" },
      ],
      applicationEvidence: [
        { label: "後続研究で確認された4項目版", itemCounts: [4], evidenceType: "empirical-short-use", summary: "ICU多職種チームとノルウェーの経営チームで、文脈調整または項目削除後の4項目構成が使用されています。原版7項目と同一ではないため、採用時は内容範囲を確認してください。", title: "Four-item applications of team psychological safety", year: 2023, doi: "10.3390/ijerph20010406", url: "https://doi.org/10.3390/ijerph20010406" },
      ],
      psychometricEvidence: [
        { label: "原著のチーム研究", sample: "製造企業の51チーム", methods: "複数方法による現場研究、チーム学習・成果との関係の検討", result: "心理的安全性が学習行動と関連し、学習行動が成果との関係を媒介", url: "https://doi.org/10.2307/2666999" },
        { label: "日本語版の検証", sample: "日本人労働者287名（1か月後236名）", methods: "内的整合性、ICC、確認的因子分析、関連尺度との相関", result: "α=.91／.88、ICC=.87で、許容可能な信頼性・妥当性を報告", url: "https://doi.org/10.2486/indhealth.2021-0130" },
      ],
      itemPublicationStatus: "not-published", items: [],
      notes: "個人の性格特性ではなく、チーム内で対人的リスクを取る安全性の共有知覚を測る。",
      recordStatus: "verified-metadata",
    },
    {
      id: "uwes-9",
      name: "Utrecht Work Engagement Scale – 9 item",
      abbreviation: "UWES-9",
      conceptId: "work-engagement",
      authors: ["Wilmar B. Schaufeli", "Arnold B. Bakker", "Marisa Salanova"],
      year: 2006,
      sourceTitle: "The Measurement of Work Engagement With a Short Questionnaire: A Cross-National Study",
      journal: "Educational and Psychological Measurement, 66(4), 701–716",
      doi: "10.1177/0013164405282471",
      itemCount: 9,
      dimensions: ["Vigor", "Dedication", "Absorption"],
      responseFormat: "7件法（0＝全くない～6＝いつも）",
      reverseItems: [], scoring: "3下位尺度、各3項目。総合得点は9項目の平均。",
      targetPopulation: ["従業員", "就業者"],
      language: "English", versionType: "short", parentScaleId: null,
      japaneseVersionStatus: "validated",
      japaneseStatusNote: "日本の3つの独立標本・計2,334名でUWES日本語版を検証した研究があり、9項目版は日本の労働者研究でも広く使用されています。",
      japaneseEvidence: [
        { kind: "psychometric-validation", label: "検証済み日本語版（UWES-J）", authors: "Shimazu et al.", year: 2008, title: "Work Engagement in Japan: Validation of the Japanese Version of the Utrecht Work Engagement Scale", doi: "10.1111/j.1464-0597.2008.00333.x", url: "https://doi.org/10.1111/j.1464-0597.2008.00333.x" },
      ],
      validationStudies: [], usagePermission: "research-use", usageEvidence: [],
      psychometricEvidence: [
        { label: "9項目短縮版の国際検証", sample: "10か国・14,521名", methods: "確認的因子分析、内的整合性、再検査信頼性、バーンアウトとの構造比較", result: "3次元9項目の許容可能な心理測定特性を報告", url: "https://doi.org/10.1177/0013164405282471" },
        { label: "日本語版の検証", sample: "日本の3独立標本・計2,334名", methods: "多母集団確認的因子分析、内的整合性、2か月再検査、構成概念妥当性", result: "1因子構造の不変性、α=.92、再検査信頼性=.66を報告", url: "https://doi.org/10.1111/j.1464-0597.2008.00333.x" },
      ],
      applicationEvidence: [
        { label: "レビューで確認された主要版", itemCounts: [17, 15, 9, 6, 3], evidenceType: "systematic-review", summary: "複数言語・地域で17、15、9、6、3項目版が検証・使用され、レビューでは9項目版が中心的な版と評価されています。", title: "Work engagement measures: A systematic literature review", year: 2024, url: "https://revistas.javeriana.edu.co/files-articulos/UPSY/23%282024%29/6972764006/" },
        { label: "特定領域レビュー内の使用版", itemCounts: [9, 17, 3], evidenceType: "systematic-review-count", summary: "長期ケア施設の看護職研究15件では、UWES-9が10件、UWES-17が3件、UWES-3が1件で使用。", title: "Antecedents and outcomes of work engagement among nursing staff in long-term care facilities", year: 2024, doi: "10.1111/jan.15804", url: "https://doi.org/10.1111/jan.15804" },
      ],
      itemPublicationStatus: "not-published", items: [],
      notes: "UWES-17、学生版UWES-Sとは区別する。研究利用条件と最新版マニュアルを確認する。",
      recordStatus: "verified-metadata",
    },
    {
      id: "davis-perceived-usefulness-scale",
      name: "Perceived Usefulness Scale",
      abbreviation: "PU",
      conceptId: "perceived-usefulness",
      authors: ["Fred D. Davis"],
      year: 1989,
      sourceTitle: "Perceived Usefulness, Perceived Ease of Use, and User Acceptance of Information Technology",
      journal: "MIS Quarterly, 13(3), 319–340",
      doi: "10.2307/249008",
      itemCount: 6,
      dimensions: ["Perceived usefulness"],
      responseFormat: "7件法",
      reverseItems: [], scoring: "単一次元6項目。対象システム名を研究文脈に合わせて設定する。",
      targetPopulation: ["情報システム利用者", "従業員", "学生"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "unconfirmed",
      japaneseStatusNote: "日本語の技術受容研究で広く用いられる概念ですが、Davisの6項目を標準化した検証済み日本語版としての根拠は今回未登録です。独自翻訳の使用と検証済み版を区別します。",
      japaneseEvidence: [],
      validationStudies: [], usagePermission: "unknown", usageEvidence: [],
      psychometricEvidence: [
        { label: "原著の尺度開発", sample: "4つの業務用アプリケーションを評価した利用者計152名", methods: "内容妥当性の予備検討、2研究での信頼性・構成概念妥当性検討", result: "知覚有用性6項目の信頼性・妥当性を支持", url: "https://doi.org/10.2307/249008" },
      ],
      applicationEvidence: [
        { label: "原版と日本語の応用研究例", itemCounts: [6, 3], evidenceType: "usage-study", summary: "Davis原版は6項目。日本のモバイルアプリ研究ではTAMを援用し、関連する知覚利便性を3項目で測定しています。これは公式3項目版ではなく、研究文脈に合わせた応用版です。", title: "オムニチャネル・ショッパーによる知覚オムニチャネル統合度がモバイル・アプリケーション受容行動等に与える影響", year: 2022, doi: "10.7222/marketing.2022.015", url: "https://doi.org/10.7222/marketing.2022.015" },
      ],
      usageStudies: [
        { title: "A Study on Technology Acceptance of Digital Healthcare among Older Korean Adults Using Extended TAM", authors: "Hoque et al.", year: 2023, context: "デジタルヘルス・ウェアラブル", sample: "韓国の高齢者170名", itemCount: 3, responseFormat: "5件法", language: "Korean", adaptation: "Venkatesh & Davisの項目をウェアラブル文脈へ調整。英語から韓国語へ翻訳・逆翻訳。", result: "負荷量=.896～.904、CR=.926、AVE=.808、α=.881。", doi: "10.3390/admsci13020042", url: "https://doi.org/10.3390/admsci13020042" },
        { title: "Exploring User Acceptance of Online Virtual Reality Exhibition Technologies: A Case Study of Liangzhu Museum", authors: "Liu et al.", year: 2024, context: "オンラインVR博物館", sample: "中国の一般利用者、有効回答314件", itemCount: 4, responseFormat: "5件法", language: "Chinese", adaptation: "Davisらを基礎に、博物館理解・訪問効率・展示情報・重要性へ文脈調整。", result: "α=.742、CR=.853、AVE=.659。", doi: "10.1371/journal.pone.0308267", url: "https://doi.org/10.1371/journal.pone.0308267" },
        { title: "オムニチャネル・ショッパーによる知覚オムニチャネル統合度がモバイル・アプリケーション受容行動等に与える影響", year: 2022, context: "日本のモバイルアプリ", sample: "日本のオムニチャネル・ショッパー（詳細は本文参照）", itemCount: 3, responseFormat: "本文参照", language: "Japanese", adaptation: "TAMを援用した知覚利便性3項目。Davisの公式短縮版ではなく文脈調整版。", doi: "10.7222/marketing.2022.015", url: "https://doi.org/10.7222/marketing.2022.015" },
      ],
      itemPublicationStatus: "not-published", items: [], verifiedAt: "2026-07-13",
      notes: "同じ原著の知覚容易性尺度と組み合わせてTAMの主要信念を測定する。",
      recordStatus: "verified-metadata",
    },
    {
      id: "davis-perceived-ease-of-use-scale",
      name: "Perceived Ease of Use Scale",
      abbreviation: "PEOU",
      conceptId: "perceived-ease-of-use",
      authors: ["Fred D. Davis"],
      year: 1989,
      sourceTitle: "Perceived Usefulness, Perceived Ease of Use, and User Acceptance of Information Technology",
      journal: "MIS Quarterly, 13(3), 319–340",
      doi: "10.2307/249008",
      itemCount: 6,
      dimensions: ["Perceived ease of use"],
      responseFormat: "7件法",
      reverseItems: [], scoring: "単一次元6項目。対象システム名を研究文脈に合わせて設定する。",
      targetPopulation: ["情報システム利用者", "従業員", "学生"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "unconfirmed",
      japaneseStatusNote: "日本語の技術受容研究で使用例は多数ありますが、Davisの6項目を標準化した検証済み日本語版としての根拠は今回未登録です。",
      japaneseEvidence: [],
      validationStudies: [], usagePermission: "unknown", usageEvidence: [],
      psychometricEvidence: [
        { label: "原著の尺度開発", sample: "4つの業務用アプリケーションを評価した利用者計152名", methods: "内容妥当性の予備検討、2研究での信頼性・構成概念妥当性検討", result: "知覚容易性6項目の信頼性・妥当性を支持", url: "https://doi.org/10.2307/249008" },
      ],
      applicationEvidence: [
        { label: "原版と日本語の応用研究例", itemCounts: [6, 5], evidenceType: "usage-study", summary: "Davis原版は6項目。日本のモバイルアプリ研究では先行研究を援用した知覚利用容易性5項目で測定しています。項目数は研究ごとに異なるため、公式短縮版とは区別します。", title: "オムニチャネル・ショッパーによる知覚オムニチャネル統合度がモバイル・アプリケーション受容行動等に与える影響", year: 2022, doi: "10.7222/marketing.2022.015", url: "https://doi.org/10.7222/marketing.2022.015" },
      ],
      usageStudies: [
        { title: "A Study on Technology Acceptance of Digital Healthcare among Older Korean Adults Using Extended TAM", authors: "Hoque et al.", year: 2023, context: "デジタルヘルス・ウェアラブル", sample: "韓国の高齢者170名", itemCount: 3, responseFormat: "5件法", language: "Korean", adaptation: "Venkatesh & Davisの項目をウェアラブル文脈へ調整。英語から韓国語へ翻訳・逆翻訳。", result: "負荷量=.887～.934、CR=.939、AVE=.838、α=.903。", doi: "10.3390/admsci13020042", url: "https://doi.org/10.3390/admsci13020042" },
        { title: "Exploring User Acceptance of Online Virtual Reality Exhibition Technologies: A Case Study of Liangzhu Museum", authors: "Liu et al.", year: 2024, context: "オンラインVR博物館", sample: "中国の一般利用者、有効回答314件", itemCount: 3, responseFormat: "5件法", language: "Chinese", adaptation: "学習容易性・習熟容易性・困難の少なさとしてVR展示文脈へ調整。", result: "α=.719、CR=.842、AVE=.640。", doi: "10.1371/journal.pone.0308267", url: "https://doi.org/10.1371/journal.pone.0308267" },
        { title: "オムニチャネル・ショッパーによる知覚オムニチャネル統合度がモバイル・アプリケーション受容行動等に与える影響", year: 2022, context: "日本のモバイルアプリ", sample: "日本のオムニチャネル・ショッパー（詳細は本文参照）", itemCount: 5, responseFormat: "本文参照", language: "Japanese", adaptation: "先行研究を援用した知覚利用容易性5項目。公式短縮版とは区別。", doi: "10.7222/marketing.2022.015", url: "https://doi.org/10.7222/marketing.2022.015" },
      ],
      itemPublicationStatus: "not-published", items: [], verifiedAt: "2026-07-13",
      notes: "同じ原著の知覚有用性尺度と組み合わせてTAMの主要信念を測定する。",
      recordStatus: "verified-metadata",
    },
    {
      id: "survey-perceived-organizational-support-36",
      name: "Survey of Perceived Organizational Support",
      abbreviation: "SPOS-36",
      conceptId: "perceived-organizational-support",
      authors: ["Robert Eisenberger", "Robin Huntington", "Steven Hutchison", "Debora Sowa"],
      year: 1986,
      sourceTitle: "Perceived Organizational Support",
      journal: "Journal of Applied Psychology, 71(3), 500–507",
      doi: "10.1037/0021-9010.71.3.500",
      itemCount: 36,
      dimensions: ["Perceived organizational support"],
      responseFormat: "7件法",
      reverseItems: [], scoring: "単一次元。逆転項目と短縮版の選択は原典・利用資料を確認。",
      targetPopulation: ["従業員", "組織成員"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "related-version",
      japaneseStatusNote: "原版に基づく日本語版SPOS-Jが国際的ガイドラインで翻訳され、項目反応理論を用いて8項目へ短縮・検証されています。原版36項目とSPOS-J 8項目は別レコードで登録しています。",
      japaneseEvidence: [
        { kind: "related-version", label: "検証済み日本語短縮版（SPOS-J）", authors: "Odagami et al.", year: 2024, title: "Reliability and validity of the Japanese version of the Survey of Perceived Organizational Support", doi: "10.1093/joccuh/uiae034", url: "https://doi.org/10.1093/joccuh/uiae034" },
      ],
      validationStudies: [], usagePermission: "unknown", usageEvidence: [],
      psychometricEvidence: [
        { label: "原著の尺度開発", sample: "9組織の従業員361名、および私立高校教員71名", methods: "主成分分析、内的整合性、欠勤・交換イデオロギーとの関係", result: "単一次元36項目、α=.97を報告", url: "https://doi.org/10.1037/0021-9010.71.3.500" },
      ],
      applicationEvidence: [
        { label: "複数短縮版の比較研究", itemCounts: [36, 16, 8, 3], evidenceType: "comparative-validation", summary: "実際に使用されてきた36・16・8・3項目版を比較し、8または16項目版は原版と同等に有効で、より効率的と報告。", title: "The survey of perceived organisational support: Which measure should we use?", year: 2009, doi: "10.4102/sajip.v35i1.754", url: "https://doi.org/10.4102/sajip.v35i1.754" },
      ],
      itemPublicationStatus: "not-published", items: [], verifiedAt: "2026-07-13",
      notes: "16・8・3項目など複数の短縮版があるため、採用した項目集合を明記する。",
      recordStatus: "verified-metadata",
    },
    {
      id: "spos-j-8",
      name: "Japanese Survey of Perceived Organizational Support – 8 item",
      abbreviation: "SPOS-J 8",
      conceptId: "perceived-organizational-support",
      authors: ["Kiminori Odagami", "Tomohisa Nagata", "Hisashi Eguchi", "Akiomi Inoue", "Kosuke Mafune", "Koji Mori"],
      year: 2024,
      sourceTitle: "Reliability and validity of the Japanese version of the Survey of Perceived Organizational Support",
      journal: "Journal of Occupational Health, 66(1), uiae034",
      doi: "10.1093/joccuh/uiae034",
      itemCount: 8,
      dimensions: ["Sufficiency of Positive Aspects", "Minimality of Negative Aspects"],
      responseFormat: "7件法",
      reverseItems: [], scoring: "2下位尺度、各4項目。原著はSPA下位尺度の使用を特に支持。",
      targetPopulation: ["日本人労働者"],
      language: "Japanese", versionType: "translated", parentScaleId: "survey-perceived-organizational-support-36",
      japaneseVersionStatus: "validated",
      japaneseStatusNote: "ISPORのガイドラインに沿って翻訳し、6,220名のベースライン調査と2週間後の追跡調査を用いて検証された日本語版です。",
      japaneseEvidence: [
        { kind: "psychometric-validation", label: "検証済み日本語版", authors: "Odagami et al.", year: 2024, title: "Reliability and validity of the Japanese version of the Survey of Perceived Organizational Support", doi: "10.1093/joccuh/uiae034", url: "https://doi.org/10.1093/joccuh/uiae034" },
      ],
      validationStudies: [], usagePermission: "unknown", usageEvidence: [],
      psychometricEvidence: [
        { label: "日本語版の開発・検証", sample: "日本人労働者6,220名、2週間後追跡452名", methods: "EFA・CFA、項目反応理論、収束・既知集団妥当性、内的整合性、再検査信頼性", result: "SPA α=.92・ICC=.72、MNA α=.84・ICC=.55。SPAの信頼性・妥当性を支持", url: "https://doi.org/10.1093/joccuh/uiae034" },
      ],
      applicationEvidence: [
        { label: "日本語版として検証された短縮版", itemCounts: [8], evidenceType: "psychometric-validation", summary: "原版SPOSを日本語化し、項目反応理論で8項目を選定。日本人労働者6,220名で検証されています。", title: "Reliability and validity of the Japanese version of the Survey of Perceived Organizational Support", year: 2024, doi: "10.1093/joccuh/uiae034", url: "https://doi.org/10.1093/joccuh/uiae034" },
      ],
      itemPublicationStatus: "not-published", items: [], verifiedAt: "2026-07-13",
      notes: "原著者の許可を得て作成された版。利用時は論文・補足資料と最新条件を確認する。",
      recordStatus: "verified-metadata",
    },
    {
      id: "lmx-7",
      name: "Leader–Member Exchange Scale – 7 item",
      abbreviation: "LMX-7",
      conceptId: "leader-member-exchange",
      authors: ["George B. Graen", "Mary Uhl-Bien"],
      year: 1995,
      sourceTitle: "Relationship-Based Approach to Leadership: Development of Leader–Member Exchange Theory of Leadership over 25 Years",
      journal: "The Leadership Quarterly, 6(2), 219–247",
      doi: "10.1016/1048-9843(95)90036-5",
      itemCount: 7,
      dimensions: ["Leader–member exchange quality"],
      responseFormat: "5件法（項目ごとに選択肢表現が異なる）",
      reverseItems: [], scoring: "7項目を合計。回答選択肢は原典を確認。",
      targetPopulation: ["部下", "従業員"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "usage-example",
      japaneseStatusNote: "原著者の許可を得て研究者と日英バイリンガル専門家が翻訳した日本語版の使用例がありますが、独立した心理測定学的検証論文としては今回登録していません。",
      japaneseEvidence: [
        { kind: "usage-example", label: "許可・専門家翻訳を経た日本語版の使用例", authors: "Kawaguchi et al.", year: 2021, title: "Relationship Between Teams’ Leader–Member Exchange Characteristics and Psychological Outcomes for Nurses and Nurse Managers", doi: "10.1177/23779608211025981", url: "https://doi.org/10.1177/23779608211025981" },
      ],
      validationStudies: [], usagePermission: "unknown", usageEvidence: [],
      psychometricEvidence: [
        { label: "理論レビューと尺度推奨", sample: "LMX研究25年のレビュー", methods: "理論発展、測定法、分析水準の整理", result: "二者関係の質を測る7項目LMX-7を推奨", url: "https://doi.org/10.1016/1048-9843(95)90036-5" },
      ],
      itemPublicationStatus: "not-published", items: [], verifiedAt: "2026-07-13",
      notes: "多次元LMX尺度（LMX-MDM）などの別尺度と区別する。",
      recordStatus: "verified-metadata",
    },
    {
      id: "job-crafting-scale-tims",
      name: "Job Crafting Scale",
      abbreviation: "JCS",
      conceptId: "job-crafting",
      authors: ["Maria Tims", "Arnold B. Bakker", "Daantje Derks"],
      year: 2012,
      sourceTitle: "Development and Validation of the Job Crafting Scale",
      journal: "Journal of Vocational Behavior, 80(1), 173–186",
      doi: "10.1016/j.jvb.2011.05.009",
      itemCount: 21,
      dimensions: ["Increasing structural job resources", "Decreasing hindering job demands", "Increasing social job resources", "Increasing challenging job demands"],
      responseFormat: "5件法",
      reverseItems: [], scoring: "4下位尺度。日本語版研究では修正5因子モデルも検討されている。",
      targetPopulation: ["従業員", "就業者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "validated",
      japaneseStatusNote: "翻訳・逆翻訳を経た21項目日本語版が、日本人従業員を対象に因子構造、内的整合性、構成概念妥当性について検証されています。",
      japaneseEvidence: [
        { kind: "psychometric-validation", label: "検証済み日本語版（JCS-J）", authors: "Eguchi et al.", year: 2016, title: "Validation of the Japanese version of the job crafting scale", doi: "10.1539/joh.15-0173-OA", url: "https://doi.org/10.1539/joh.15-0173-OA" },
      ],
      validationStudies: [], usagePermission: "unknown", usageEvidence: [],
      psychometricEvidence: [
        { label: "原著の尺度開発", sample: "オランダの従業員を対象とする2研究", methods: "因子構造、信頼性、収束・基準関連妥当性、同僚評定との関係", result: "4次元21項目を支持", url: "https://doi.org/10.1016/j.jvb.2011.05.009" },
        { label: "日本語版の検証", sample: "日本人従業員を対象とするWeb調査", methods: "確認的因子分析、内的整合性、収束・弁別妥当性", result: "JCS-Jを日本の文脈で使用できる尺度として支持", url: "https://doi.org/10.1539/joh.15-0173-OA" },
      ],
      itemPublicationStatus: "not-published", items: [], verifiedAt: "2026-07-13",
      notes: "Wrzesniewski & Dutton系の認知的・関係的クラフティング尺度などとは理論枠組みが異なる。",
      recordStatus: "verified-metadata",
    },
    {
      id: "maslach-burnout-inventory-general-survey",
      name: "Maslach Burnout Inventory – General Survey",
      abbreviation: "MBI-GS",
      conceptId: "burnout",
      authors: ["Wilmar B. Schaufeli", "Michael P. Leiter", "Christina Maslach", "Susan E. Jackson"],
      year: 1996,
      sourceTitle: "Maslach Burnout Inventory – General Survey",
      journal: "The Maslach Burnout Inventory Manual, 3rd ed., pp. 19–26",
      doi: "",
      itemCount: 16,
      dimensions: ["Exhaustion", "Cynicism", "Professional efficacy"],
      responseFormat: "7件法（0＝全くない～6＝毎日）",
      reverseItems: [], scoring: "3下位尺度。単一の総合バーンアウト得点に統合しない。",
      targetPopulation: ["職種を問わない従業員", "就業者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "validated",
      japaneseStatusNote: "病院職員を対象に3因子構造と構成概念妥当性を検討した日本語研究版があります。公式な利用にはライセンスと提供翻訳の確認が必要です。",
      japaneseEvidence: [
        { kind: "psychometric-validation", label: "日本語研究版の検証", authors: "Kitaoka-Higashiguchi, Ogino, & Masuda", year: 2004, title: "Validation of Japanese research version of Maslach Burnout Inventory-General Survey", doi: "10.4992/jjpsy.75.415", url: "https://doi.org/10.4992/jjpsy.75.415" },
      ],
      validationStudies: [], usagePermission: "permission-required", usageEvidence: [],
      psychometricEvidence: [
        { label: "日本語研究版の検証", sample: "病院職員", methods: "探索的・確認的因子分析、仕事特性との関連による構成概念妥当性", result: "原版と同じ3次元を概ね支持", url: "https://doi.org/10.4992/jjpsy.75.415" },
      ],
      itemPublicationStatus: "not-published", items: [], verifiedAt: "2026-07-13",
      notes: "Mind Gardenから実施数に応じたライセンス購入が必要。項目を公開Webに掲載できないため、本アトラスでは本文を収録しない。",
      recordStatus: "verified-metadata",
    },
    {
      id: "domain-specific-innovativeness-scale",
      name: "Domain-Specific Innovativeness Scale",
      abbreviation: "DSI",
      conceptId: "consumer-innovativeness",
      authors: ["Ronald E. Goldsmith", "Charles F. Hofacker"],
      year: 1991,
      sourceTitle: "Measuring Consumer Innovativeness",
      journal: "Journal of the Academy of Marketing Science, 19(3), 209–221",
      doi: "10.1177/009207039101900306",
      itemCount: 6,
      dimensions: ["Domain-specific consumer innovativeness"],
      responseFormat: "5件法",
      reverseItems: [], scoring: "単一次元。肯定3項目・否定3項目で、対象製品領域を設問に設定する。",
      targetPopulation: ["消費者", "特定製品カテゴリーの利用者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "unconfirmed",
      japaneseStatusNote: "日本語研究での使用可能性はありますが、DSI 6項目の翻訳・心理測定学的検証を明示した日本語版根拠は今回未登録です。",
      japaneseEvidence: [],
      validationStudies: [], usagePermission: "unknown", usageEvidence: [],
      psychometricEvidence: [
        { label: "原著の尺度開発", sample: "複数の製品領域を扱う6研究", methods: "信頼性、収束・弁別・予測妥当性、領域間での適用可能性の検討", result: "領域固有の革新性を測る単一次元6項目を支持", url: "https://doi.org/10.1177/009207039101900306" },
        { label: "追試による検証", sample: "経営学専攻学生247名", methods: "単一次元性、黙従反応、法則的・基準関連妥当性", result: "単一次元性と複数の妥当性証拠を報告", url: "https://doi.org/10.1177/0013164493053004023" },
      ],
      itemPublicationStatus: "not-published", items: [], verifiedAt: "2026-07-13",
      notes: "一般的な個人革新性ではなく、音楽・衣料・技術など指定した領域内での早期採用傾向を測る。",
      recordStatus: "verified-metadata",
    },
    {
      id: "uwes-3",
      name: "Utrecht Work Engagement Scale – 3 item",
      abbreviation: "UWES-3",
      conceptId: "work-engagement",
      authors: ["Wilmar B. Schaufeli", "Akihito Shimazu", "Jari Hakanen", "Marisa Salanova", "Hans De Witte"],
      year: 2019,
      sourceTitle: "An Ultra-Short Measure for Work Engagement: The UWES-3 Validation Across Five Countries",
      journal: "European Journal of Psychological Assessment, 35(4), 577–591",
      doi: "10.1027/1015-5759/a000430",
      itemCount: 3,
      dimensions: ["Vigor", "Dedication", "Absorption（各1項目）"],
      responseFormat: "7件法（0＝全くない～6＝いつも）",
      reverseItems: [], scoring: "3項目の平均。下位尺度得点ではなく、仕事へのエンゲージメント全体を簡潔に測る。",
      targetPopulation: ["従業員", "就業者"],
      language: "English / Japanese and other languages", versionType: "short", parentScaleId: "uwes-9",
      japaneseVersionStatus: "validated",
      japaneseStatusNote: "日本1,968名を含む5か国の大規模標本でUWES-3が検証されています。日本語で使う際は、当該研究で用いられた項目表現と最新版マニュアルを確認してください。",
      japaneseEvidence: [
        { kind: "psychometric-validation", label: "日本を含む5か国でのUWES-3検証", authors: "Schaufeli et al.", year: 2019, title: "An Ultra-Short Measure for Work Engagement: The UWES-3 Validation Across Five Countries", doi: "10.1027/1015-5759/a000430", url: "https://doi.org/10.1027/1015-5759/a000430" },
      ],
      validationStudies: [], usagePermission: "research-use", usageEvidence: [],
      psychometricEvidence: [
        { label: "5か国での超短縮版検証", sample: "フィンランド22,117名、日本1,968名、オランダ38,278名、ベルギー5,062名、スペイン10,040名", methods: "因子構造、信頼性、UWES-9との共有分散、関連概念との相関パターンを比較", result: "UWES-9の分散の86～92%を共有し、関連概念との相関差は平均絶対値.02", url: "https://doi.org/10.1027/1015-5759/a000430" },
        { label: "独立標本での追試", sample: "ペルー・リマの就業者200名", methods: "内的整合性、因子構造、外的妥当性", result: "信頼性.94と1因子構造を報告", url: "https://doi.org/10.3390/ijerph19020890" },
      ],
      applicationEvidence: [
        { label: "後続研究で検証された3項目版", itemCounts: [3], evidenceType: "cross-national-validation", summary: "活力・熱意・没頭を各1項目で代表。5か国の大規模データで9項目版との近い関連パターンが確認されています。", title: "An Ultra-Short Measure for Work Engagement: The UWES-3 Validation Across Five Countries", year: 2019, doi: "10.1027/1015-5759/a000430", url: "https://doi.org/10.1027/1015-5759/a000430" },
      ],
      usageStudies: [
        { title: "Factors Associated With Work Engagement of Nurses During the Fifth Wave of the COVID-19 Pandemic in Japan", authors: "Muroi et al.", year: 2023, context: "日本の看護職", sample: "千葉・東京の看護師187名", itemCount: 3, responseFormat: "7件法", language: "Japanese", adaptation: "UWES-3で仕事へのエンゲージメントを測定し、JD-Rモデルの関連要因を検討。", result: "COVID-19関連ストレス、所属部署、金銭的報酬等との関連を回帰分析。", doi: "10.2196/45830", url: "https://doi.org/10.2196/45830" },
        { title: "Validation of the Work Engagement Scale-3, Used in the 5th Korean Working Conditions Survey", authors: "Choi et al.", year: 2020, context: "韓国の全国就業者調査", sample: "第5回韓国労働条件調査50,205名", itemCount: 3, responseFormat: "本文参照", language: "Korean", adaptation: "活力・熱意はUWES-3と同じだが、没頭項目が異なるWES-3。完全に同一の版とはみなさない。", result: "α=.776、CFI=.994、RMSEA=.043。", doi: "10.35371/aoem.2020.32.e27", url: "https://doi.org/10.35371/aoem.2020.32.e27" },
        { title: "Daily Challenge-Hindrance Stress and Work Engagement in Preschool Teacher: The Role of Affect and Mindfulness", authors: "Zhang et al.", year: 2024, context: "日誌・経験サンプリング", sample: "上海の幼稚園教員220名、5勤務日", itemCount: 3, responseFormat: "5件法", language: "Chinese", adaptation: "UWES-3を毎日の仕事へのエンゲージメントに合わせて使用。", result: "5時点のα=.860～.934（平均.908）。", doi: "10.1186/s12889-024-20255-9", url: "https://doi.org/10.1186/s12889-024-20255-9" },
      ],
      itemPublicationStatus: "not-published", items: [], verifiedAt: "2026-07-13",
      notes: "回答負担を最小化したい調査向け。3次元を各1項目で代表するため、次元別の精密な診断にはUWES-9等を検討する。",
      recordStatus: "verified-metadata",
    },
    {
      id: "moaq-job-satisfaction-subscale",
      name: "Michigan Organizational Assessment Questionnaire Job Satisfaction Subscale",
      abbreviation: "MOAQ-JSS",
      conceptId: "job-satisfaction",
      authors: ["Cortlandt Cammann", "Mark Fichman", "Douglas Jenkins", "John Klesh"],
      year: 1983,
      sourceTitle: "Assessing the Attitudes and Perceptions of Organizational Members",
      journal: "Assessing Organizational Change: A Guide to Methods, Measures, and Practices, pp. 71–138",
      doi: "",
      itemCount: 3,
      dimensions: ["Overall job satisfaction"],
      responseFormat: "7件法",
      reverseItems: [2], scoring: "第2項目を逆転後、3項目を平均または合計。採用研究の得点化を確認する。",
      targetPopulation: ["従業員", "就業者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "unconfirmed",
      japaneseStatusNote: "日本語研究での利用可能性はありますが、標準化されたMOAQ-JSS日本語版の翻訳・心理測定学的検証根拠は今回未登録です。",
      japaneseEvidence: [],
      validationStudies: [], usagePermission: "unknown", usageEvidence: [],
      psychometricEvidence: [
        { label: "メタ分析による構成概念妥当性", sample: "MOAQ-JSSを用いた研究のメタ分析", methods: "信頼性、収束・弁別妥当性、関連変数との関係を統合", result: "3項目尺度の構成概念妥当性を包括的に検討", url: "https://doi.org/10.1016/j.jvb.2008.01.004" },
      ],
      applicationEvidence: [
        { label: "後続研究を統合した3項目版の検証", itemCounts: [3], evidenceType: "meta-analysis", summary: "全般的職務満足を3項目で測る既存下位尺度について、後続研究を統合したメタ分析で妥当性が検討されています。", title: "A Meta-Analytic Examination of the Construct Validity of the Michigan Organizational Assessment Questionnaire Job Satisfaction Subscale", year: 2008, doi: "10.1016/j.jvb.2008.01.004", url: "https://doi.org/10.1016/j.jvb.2008.01.004" },
      ],
      usageStudies: [
        { title: "Relationships Between Work Outcomes, Work Attitudes and Work Environments of Health Support Workers in Ontario Long-Term Care and Home and Community Care Settings", authors: "Berta et al.", year: 2018, context: "カナダの高齢者ケア", sample: "オンタリオ州のヘルスサポートワーカー460名", itemCount: 3, responseFormat: "7件法", language: "English", adaptation: "MOAQ-JSS全3項目を、他の仕事態度・職場環境・成果尺度と同じ調査に組み込んだ。", result: "全尺度でα>.70。職務満足は仕事へのエンゲージメント等と有意に関連。", doi: "10.1186/s12960-018-0277-9", url: "https://doi.org/10.1186/s12960-018-0277-9" },
        { title: "The Association Between Workplace Ostracism and Knowledge-Sharing Behaviors Among Chinese University Teachers", authors: "Wang et al.", year: 2023, context: "中国の大学教員", sample: "中国の大学教員388名", itemCount: 3, responseFormat: "5件法", language: "Chinese", adaptation: "中国語で検証されたMOAQ-JSSを使用し、3項目平均を算出。", result: "α=.94。4因子測定モデル CFI=.96、RMSEA=.05。", doi: "10.3389/fpsyg.2023.1030043", url: "https://doi.org/10.3389/fpsyg.2023.1030043" },
        { title: "Exploring Types of Telecommuters: A Latent Class Analysis Approach", authors: "Vanderstukken et al.", year: 2022, context: "テレワークの縦断研究", sample: "テレワーカー（2時点、詳細は本文参照）", itemCount: 3, responseFormat: "5件法", language: "Dutch / study context", adaptation: "MOAQ-JSS 3項目を2時点で使用。", result: "T1 α=.85、T2 α=.88。", doi: "10.1080/1359432X.2021.1952989", url: "https://doi.org/10.1080/1359432X.2021.1952989" },
      ],
      itemPublicationStatus: "not-published", items: [], verifiedAt: "2026-07-13",
      notes: "職務満足の個別側面ではなく全般的満足を短く測る。原尺度にDOIがないため、DOIリンクは後続のメタ分析検証を登録。",
      recordStatus: "verified-metadata",
    },
    {
      id: "brief-index-affective-job-satisfaction",
      name: "Brief Index of Affective Job Satisfaction",
      abbreviation: "BIAJS",
      conceptId: "job-satisfaction",
      authors: ["Edmund R. Thompson", "Florence T. T. Phua"],
      year: 2012,
      sourceTitle: "A Brief Index of Affective Job Satisfaction",
      journal: "Group & Organization Management, 37(3), 275–307",
      doi: "10.1177/1059601111434201",
      itemCount: 4,
      dimensions: ["Affective job satisfaction"],
      responseFormat: "5件法",
      reverseItems: [], scoring: "4項目を平均または合計。認知的評価より、仕事に対する感情的な満足を測る。",
      targetPopulation: ["従業員", "就業者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "unconfirmed",
      japaneseStatusNote: "BIAJS 4項目の標準化された検証済み日本語版は今回未登録です。独自翻訳を使用する場合は翻訳手続と測定特性を報告してください。",
      japaneseEvidence: [],
      validationStudies: [], usagePermission: "unknown", usageEvidence: [],
      psychometricEvidence: [
        { label: "4項目尺度の開発・検証", sample: "質的研究計28名、量的研究計901名", methods: "内的整合性、時間的安定性、収束・基準関連妥当性、国籍・職位・職種間の測定不変性", result: "簡潔な感情的職務満足尺度として複数の妥当性根拠を報告", url: "https://doi.org/10.1177/1059601111434201" },
      ],
      applicationEvidence: [
        { label: "複数標本で開発・検証された4項目版", itemCounts: [4], evidenceType: "scale-development", summary: "4項目で感情的職務満足を測定。複数標本で信頼性・妥当性と集団間の測定不変性が検討されています。", title: "A Brief Index of Affective Job Satisfaction", year: 2012, doi: "10.1177/1059601111434201", url: "https://doi.org/10.1177/1059601111434201" },
      ],
      usageStudies: [
        { title: "The Mediating Role of Perceived Emotional Intelligence: Examining the Impact of Affective Job Satisfaction on Organizational Identification Among Chinese Technological Workers", authors: "Cano Ibarra et al.", year: 2024, context: "中国の技術職", sample: "中国の技術職392名", itemCount: 4, responseFormat: "5件法", language: "Chinese", adaptation: "BIAJSを中国語へ逆翻訳し、感情的職務満足として使用。", result: "α=.92、単一次元。", doi: "10.3389/fpsyg.2024.1285853", url: "https://doi.org/10.3389/fpsyg.2024.1285853" },
        { title: "Validation of the Kazakh Version of the Brief Index of Affective Job Satisfaction in Medical Universities Faculty Staff Sample", authors: "Uristemova et al.", year: 2023, context: "カザフスタンの医科大学", sample: "医科大学教員715名", itemCount: 4, responseFormat: "本文参照", language: "Kazakh", adaptation: "WHOの翻訳・適応手順に沿ってBIAJSをカザフ語化。", result: "項目間相関 r=.616～.716。", doi: "10.23950/jcmk/12928", url: "https://doi.org/10.23950/jcmk/12928" },
      ],
      itemPublicationStatus: "not-published", items: [], verifiedAt: "2026-07-13",
      notes: "JSSのような多面的職務満足ではなく、全般的な感情的満足を短く測る。研究目的との概念適合を確認する。",
      recordStatus: "verified-metadata",
    },
    {
      id: "overall-brand-equity-scale",
      name: "Overall Brand Equity Scale",
      abbreviation: "OBE",
      conceptId: "consumer-based-brand-equity",
      authors: ["Boonghee Yoo", "Naveen Donthu"],
      year: 2001,
      sourceTitle: "Developing and Validating a Multidimensional Consumer-Based Brand Equity Scale",
      journal: "Journal of Business Research, 52(1), 1–14",
      doi: "10.1016/S0148-2963(99)00098-3",
      itemCount: 4,
      dimensions: ["Overall brand equity"],
      responseFormat: "5件法",
      reverseItems: [], scoring: "4項目を平均。ブランド名によって生じる総合的な付加価値を比較する。",
      targetPopulation: ["消費者", "ブランド利用者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "unconfirmed",
      japaneseStatusNote: "日本語研究で使用される可能性はありますが、OBE 4項目の標準化された検証済み日本語版は今回未登録です。",
      japaneseEvidence: [],
      validationStudies: [], usagePermission: "unknown", usageEvidence: [],
      psychometricEvidence: [
        { label: "原著内の4項目総合尺度", sample: "米国人・韓国系米国人・韓国人を含む多文化標本、複数ブランド", methods: "尺度開発、因子構造、信頼性、収束・弁別・既知集団妥当性", result: "10項目の多次元尺度とは別に、4項目の総合ブランド・エクイティ尺度を提示", url: "https://doi.org/10.1016/S0148-2963(99)00098-3" },
      ],
      applicationEvidence: [
        { label: "総合評価に使える4項目尺度", itemCounts: [4], evidenceType: "scale-development", summary: "ブランド・ロイヤルティ、知覚品質、認知・連想を別々に診断する10項目版に対し、ブランドの総合的付加価値を4項目で測ります。", title: "Developing and Validating a Multidimensional Consumer-Based Brand Equity Scale", year: 2001, doi: "10.1016/S0148-2963(99)00098-3", url: "https://doi.org/10.1016/S0148-2963(99)00098-3" },
      ],
      usageStudies: [
        { title: "Measuring Brand Equity: An Evaluation of a Consumer-Based Brand Equity Scale", authors: "Washburn & Plank", year: 2002, context: "独立追試・別ブランド文脈", sample: "消費者標本（詳細は本文参照）", itemCount: 4, responseFormat: "本文参照", language: "English", adaptation: "Yoo & Donthuの多次元尺度と4項目OBEを別文脈で一部修正して独立評価。", result: "原尺度の頑健性と測定上の改善点を検討。", doi: "10.1080/10696679.2002.11501909", url: "https://doi.org/10.1080/10696679.2002.11501909" },
        { title: "Marketing Mix Effects on Private Labels Brand Equity", authors: "Abril & Rodriguez-Cánovas", year: 2016, context: "スペインのプライベートブランド", sample: "ヨーグルトのPB購入者450名", itemCount: 4, responseFormat: "7件法", language: "Spanish", adaptation: "Yooらの4項目OBEを、ブランド名によるPB商品の付加価値測定に適用。", result: "全構成概念でα>.70、CR>.60、AVE>.50。", doi: "10.1016/j.redeen.2016.09.003", url: "https://doi.org/10.1016/j.redeen.2016.09.003" },
        { title: "Testing Cross-Culture Invariance of the Brand Equity Creation Process", authors: "Yoo & Donthu", year: 2002, context: "米国・韓国の文化比較", sample: "米国・韓国の消費者標本（詳細は本文参照）", itemCount: 4, responseFormat: "本文参照", language: "English / Korean", adaptation: "4名の日英・韓英バイリンガルが曖昧さを減らすため一部項目を修正し、文化間不変性を検討。", result: "OBEの信頼性は高く、ブランド・エクイティ形成過程の文化差を検討。", doi: "10.1108/10610420210445505", url: "https://doi.org/10.1108/10610420210445505" },
      ],
      itemPublicationStatus: "not-published", items: [], verifiedAt: "2026-07-13",
      notes: "同じ原著の10項目多次元尺度とは用途が異なる。総合比較には4項目OBE、次元別診断には多次元尺度を検討する。",
      recordStatus: "verified-metadata",
    },
  ],
};
