// 初期実データ版（2026-07-13確認）。尺度項目本文は収録しない。
// DOI、原典、項目数、下位次元は原著論文または公式資料で確認。
const ATLAS_DATA = {
  meta: {
    version: "0.2.0",
    status: "initial-real-data",
    updated: "2026-07-13",
    scope: "5概念・8尺度",
  },

  concepts: [
    {
      id: "brand-experience",
      nameJa: "ブランド経験",
      nameEn: "Brand Experience",
      definitionJa: "ブランドに関連する刺激によって生じる感覚・感情・認知・行動上の反応。",
      domain: "ブランド・消費者経験",
      relatedConcepts: ["brand-attachment"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1509/jmkg.73.3.52"],
    },
    {
      id: "brand-attachment",
      nameJa: "ブランド愛着",
      nameEn: "Brand Attachment",
      definitionJa: "ブランドと自己との結びつき、およびブランドに関する思考や感情の顕著性から捉える結合の強さ。",
      domain: "ブランド・消費者経験",
      relatedConcepts: ["brand-experience"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1509/jmkg.74.6.1"],
    },
    {
      id: "sense-of-agency",
      nameJa: "主体感",
      nameEn: "Sense of Agency",
      definitionJa: "自分が行為や経験の開始者・制御者であると感じる主観的経験。一般的信念を測る尺度と、特定状況での変化を測る尺度がある。",
      domain: "身体性・没入・主体感",
      relatedConcepts: ["presence", "flow"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.3389/fpsyg.2017.01552", "10.1016/j.concog.2013.04.003"],
    },
    {
      id: "presence",
      nameJa: "プレゼンス",
      nameEn: "Presence",
      definitionJa: "媒介された環境、とくに仮想環境やメディア環境の中に実際に存在しているように感じる経験。",
      domain: "身体性・没入・主体感",
      relatedConcepts: ["sense-of-agency", "flow"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1162/105474601300343612"],
    },
    {
      id: "flow",
      nameJa: "フロー",
      nameEn: "Flow",
      definitionJa: "活動へ深く集中し、行為と意識の融合、統制感、時間感覚の変化などを伴う最適経験。",
      domain: "身体性・没入・主体感",
      relatedConcepts: ["presence", "sense-of-agency"],
      parentConcepts: [], childConcepts: [], typicalAntecedents: [], typicalOutcomes: [],
      references: ["10.1123/jsep.18.1.17", "10.1123/jsep.30.5.561"],
    },
  ],

  scales: [
    {
      id: "brand-experience-scale",
      name: "Brand Experience Scale",
      abbreviation: "BXS",
      conceptId: "brand-experience",
      authors: ["J. Joško Brakus", "Bernd H. Schmitt", "Lia Zarantonello"],
      year: 2009,
      sourceTitle: "Brand Experience: What Is It? How Is It Measured? Does It Affect Loyalty?",
      journal: "Journal of Marketing, 73(3), 52–68",
      doi: "10.1509/jmkg.73.3.52",
      itemCount: 12,
      dimensions: ["Sensory", "Affective", "Intellectual", "Behavioral"],
      responseFormat: "7件法",
      reverseItems: [], scoring: "4下位次元。得点化は原典を確認。",
      targetPopulation: ["消費者", "ブランド利用者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "unconfirmed",
      japaneseStatusNote: "Brakus尺度そのものの検証済み日本語版・日本語使用例は、今回の確認範囲では登録していません。",
      japaneseEvidence: [
        { kind: "context-reference", label: "日本的ブランド経験尺度開発に向けた概念・尺度検討", title: "「ブランド経験」概念の意義と展開", year: 2016, doi: "10.7222/marketing.2016.029", url: "https://doi.org/10.7222/marketing.2016.029" },
      ],
      validationStudies: [], usagePermission: "unknown",
      itemPublicationStatus: "not-published", items: [],
      notes: "日本語での研究・予備的検討はあるが、検証済み日本語版としては未登録。",
      recordStatus: "verified-metadata",
    },
    {
      id: "brand-attachment-scale-park",
      name: "Brand Attachment Scale",
      abbreviation: "BAS",
      conceptId: "brand-attachment",
      authors: ["C. Whan Park", "Deborah J. MacInnis", "Joseph Priester", "Andreas B. Eisingerich", "Dawn Iacobucci"],
      year: 2010,
      sourceTitle: "Brand Attachment and Brand Attitude Strength: Conceptual and Empirical Differentiation of Two Critical Brand Equity Drivers",
      journal: "Journal of Marketing, 74(6), 1–17",
      doi: "10.1509/jmkg.74.6.1",
      itemCount: 4,
      dimensions: ["Brand–self connection", "Brand prominence"],
      responseFormat: "11件法（0–10）",
      reverseItems: [], scoring: "各次元2項目。得点化は原典を確認。",
      targetPopulation: ["消費者", "ブランド利用者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "unconfirmed",
      japaneseStatusNote: "Parkらの4項目版そのものの日本語版・日本語使用例は、今回の確認範囲では登録していません。",
      japaneseEvidence: [],
      validationStudies: [], usagePermission: "unknown",
      itemPublicationStatus: "not-published", items: [],
      notes: "原著では8項目版との比較後、簡潔な4項目版を採用。",
      recordStatus: "verified-metadata",
    },
    {
      id: "sense-of-agency-scale",
      name: "Sense of Agency Scale",
      abbreviation: "SoAS",
      conceptId: "sense-of-agency",
      authors: ["Adam Tapal", "Ela Oren", "Reuven Dar", "Baruch Eitam"],
      year: 2017,
      sourceTitle: "The Sense of Agency Scale: A Measure of Consciously Perceived Control over One's Mind, Body, and the Immediate Environment",
      journal: "Frontiers in Psychology, 8, 1552",
      doi: "10.3389/fpsyg.2017.01552",
      itemCount: 13,
      dimensions: ["Sense of Positive Agency (SoPA)", "Sense of Negative Agency (SoNA)"],
      responseFormat: "5件法",
      reverseItems: [], scoring: "2下位尺度。原典の因子構造と得点化を確認。",
      targetPopulation: ["一般成人"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "validated",
      japaneseStatusNote: "J-SoASは、原版と同じ2因子・13項目について、日本の20～60代8,237名を対象に信頼性・構成概念妥当性・年齢群間の構造を検討した研究で報告されています。",
      japaneseEvidence: [
        { kind: "psychometric-validation", label: "検証済み日本語版（J-SoAS）", authors: "Xu, Legaspi, Ishikawa, & Washida", year: 2024, title: "Measuring general sense of agency: a Japanese adaptation and validation of the sense of agency scale (J-SoAS)", doi: "10.3389/fpsyg.2024.1427169", url: "https://doi.org/10.3389/fpsyg.2024.1427169" },
      ],
      validationStudies: [], usagePermission: "unknown",
      itemPublicationStatus: "not-published", items: [],
      notes: "特定課題ではなく、文脈横断的・一般的な主体感の信念を測定。原著はオープンアクセス。",
      recordStatus: "verified-metadata",
    },
    {
      id: "sense-of-agency-rating-scale",
      name: "Sense of Agency Rating Scale",
      abbreviation: "SOARS",
      conceptId: "sense-of-agency",
      authors: ["Vince Polito", "Amanda J. Barnier", "Erik Z. Woody"],
      year: 2013,
      sourceTitle: "Developing the Sense of Agency Rating Scale (SOARS): An Empirical Measure of Agency Disruption in Hypnosis",
      journal: "Consciousness and Cognition, 22(3), 684–696",
      doi: "10.1016/j.concog.2013.04.003",
      itemCount: 10,
      dimensions: ["Involuntariness", "Effortlessness"],
      responseFormat: "7件法",
      reverseItems: [1, 2, 3, 5, 10], scoring: "2下位尺度、各5項目。原典を確認。",
      targetPopulation: ["催眠参加者", "特定経験後の参加者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "unconfirmed",
      japaneseStatusNote: "SOARSそのものの日本語版・日本語使用例は、今回の確認範囲では登録していません。SoASや日本独自の主体感尺度とは別尺度です。",
      japaneseEvidence: [],
      validationStudies: [], usagePermission: "unknown",
      itemPublicationStatus: "not-published", items: [],
      notes: "催眠中の主体感変容を測る目的で開発。一般的な主体感尺度SoASとは用途が異なる。",
      recordStatus: "verified-metadata",
    },
    {
      id: "itc-sopi",
      name: "ITC-Sense of Presence Inventory",
      abbreviation: "ITC-SOPI",
      conceptId: "presence",
      authors: ["Jane Lessiter", "Jonathan Freeman", "Edmund Keogh", "Jules Davidoff"],
      year: 2001,
      sourceTitle: "A Cross-Media Presence Questionnaire: The ITC-Sense of Presence Inventory",
      journal: "Presence: Teleoperators & Virtual Environments, 10(3), 282–297",
      doi: "10.1162/105474601300343612",
      itemCount: 44,
      dimensions: ["Sense of Physical Space", "Engagement", "Ecological Validity", "Negative Effects"],
      responseFormat: "5件法",
      reverseItems: [], scoring: "4下位尺度。得点化は原典を確認。",
      targetPopulation: ["メディア利用者", "VR利用者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "usage-example",
      japaneseStatusNote: "日本語への翻訳・改変を用いた研究例を確認していますが、尺度全体の心理測定学的な日本語版検証は未登録です。",
      japaneseEvidence: [
        { kind: "usage-example", label: "日本語訳・改変版の使用例", title: "SCSQ-VRを用いた研究での日本語訳・改変版ITC-SOPI", year: 2025, url: "https://www.ieice.org/publications/proceedings/bin/pdf_link.php?fname=09_kamada2.pdf&iconf=KICSS&lang=E&number=9&vol=95&year=2025" },
      ],
      validationStudies: [], usagePermission: "unknown",
      itemPublicationStatus: "not-published", items: [],
      notes: "インタラクティブ・非インタラクティブ双方のメディアを横断して測定する設計。",
      recordStatus: "verified-metadata",
    },
    {
      id: "igroup-presence-questionnaire",
      name: "Igroup Presence Questionnaire",
      abbreviation: "IPQ",
      conceptId: "presence",
      authors: ["Thomas Schubert", "Frank Friedmann", "Holger Regenbrecht"],
      year: 2001,
      sourceTitle: "The Experience of Presence: Factor Analytic Insights",
      journal: "Presence: Teleoperators & Virtual Environments, 10(3), 266–281",
      doi: "10.1162/105474601300343603",
      itemCount: 14,
      dimensions: ["Spatial Presence", "Involvement", "Experienced Realism", "General Presence item"],
      responseFormat: "7段階（−3～+3）",
      reverseItems: [], scoring: "3下位尺度と一般項目。公式資料を確認。",
      targetPopulation: ["VR利用者"],
      language: "German / English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "linguistic-validated",
      japaneseStatusNote: "公式サイトの非公式訳とは別に、順翻訳・逆翻訳・専門家レビュー・認知面接・原著者確認を経た日本語版が報告されています。信頼性・構成概念妥当性の検証は今後の課題と明記されています。",
      japaneseEvidence: [
        { kind: "linguistic-validation", label: "言語的妥当性を確認した日本語版", authors: "甘利ほか", year: 2025, title: "言語的妥当性を担保した日本語版 Igroup Presence Questionnaire の作成", doi: "10.7876/jmvr.24.1", url: "https://doi.org/10.7876/jmvr.24.1" },
      ],
      validationStudies: [], usagePermission: "unknown",
      itemPublicationStatus: "not-published", items: [],
      notes: "公式IPQサイトで尺度情報と各言語版が案内されている。日本語版の妥当性検証は未登録。",
      recordStatus: "verified-metadata",
    },
    {
      id: "sense-of-agency-scale-asai",
      name: "Sense of Agency Scale",
      abbreviation: "SOAS（浅井ほか）",
      conceptId: "sense-of-agency",
      authors: ["Tomohisa Asai", "Keisuke Takano", "Eriko Sugimori", "Yoshihiko Tanno"],
      year: 2009,
      sourceTitle: "Development of the Sense of Agency Scale and Its Factor Structure",
      journal: "The Japanese Journal of Psychology, 80(5), 414–421",
      doi: "10.4992/jjpsy.80.414",
      itemCount: 17,
      dimensions: ["心的状態への主体帰属の誤り", "身体活動の統制欠如", "社会的活動での自己主張"],
      responseFormat: "原典を確認",
      reverseItems: [], scoring: "3因子17項目。得点化は原典を確認。",
      targetPopulation: ["日本語話者の一般成人"],
      language: "Japanese", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "original-japanese",
      japaneseStatusNote: "日本語で開発され、4回の縦断調査を通じて信頼性・妥当性が報告された主体感尺度です。TapalらのSoASとは目的・因子構造が異なります。",
      japaneseEvidence: [
        { kind: "original-japanese", label: "日本語で開発・検証された尺度", authors: "浅井・高野・杉森・丹野", year: 2009, title: "自己主体感を測定する尺度の開発と因子構造の探索", doi: "10.4992/jjpsy.80.414", url: "https://doi.org/10.4992/jjpsy.80.414" },
      ],
      validationStudies: [], usagePermission: "unknown",
      itemPublicationStatus: "not-published", items: [],
      notes: "Tapalらの一般的主体感尺度（SoAS）と名称が近いが、別に開発された日本語尺度。",
      recordStatus: "verified-metadata",
    },
    {
      id: "flow-state-scale",
      name: "Flow State Scale",
      abbreviation: "FSS",
      conceptId: "flow",
      authors: ["Susan A. Jackson", "Herbert W. Marsh"],
      year: 1996,
      sourceTitle: "Development and Validation of a Scale to Measure Optimal Experience: The Flow State Scale",
      journal: "Journal of Sport & Exercise Psychology, 18(1), 17–35",
      doi: "10.1123/jsep.18.1.17",
      itemCount: 36,
      dimensions: ["Challenge–skill balance", "Action–awareness merging", "Clear goals", "Unambiguous feedback", "Concentration", "Sense of control", "Loss of self-consciousness", "Transformation of time", "Autotelic experience"],
      responseFormat: "5件法",
      reverseItems: [], scoring: "9下位尺度、各4項目。得点化は原典を確認。",
      targetPopulation: ["スポーツ・身体活動参加者"],
      language: "English", versionType: "original", parentScaleId: null,
      japaneseVersionStatus: "translation-study",
      japaneseStatusNote: "原版FSSの日本語版について、因子構造を扱う日本語版の検討が報告されています。別途、改訂版FSS-2の日本語版では信頼性・因子妥当性の検証があります。",
      japaneseEvidence: [
        { kind: "translation-study", label: "原版FSSの日本語版の検討", authors: "川端・張本", year: 2000, title: "Flow State Scale（日本語版）の検討：その1", doi: "10.20693/jspeconf.51.0_183", url: "https://doi.org/10.20693/jspeconf.51.0_183" },
        { kind: "related-version", label: "改訂版FSS-2の検証済み日本語版", authors: "Kawabata, Mallett, & Jackson", year: 2008, title: "The Flow State Scale-2 and Dispositional Flow Scale-2: Examination of factorial validity and reliability for Japanese adults", doi: "10.1016/j.psychsport.2007.05.005", url: "https://doi.org/10.1016/j.psychsport.2007.05.005" },
      ],
      validationStudies: [], usagePermission: "unknown",
      itemPublicationStatus: "not-published", items: [],
      notes: "状態としてのフローを多次元で測る原版。",
      recordStatus: "verified-metadata",
    },
    {
      id: "short-flow-state-scale-2",
      name: "Short Flow State Scale-2",
      abbreviation: "S FSS-2",
      conceptId: "flow",
      authors: ["Susan A. Jackson", "Andrew J. Martin", "Robert C. Eklund"],
      year: 2008,
      sourceTitle: "Long and Short Measures of Flow: The Construct Validity of the FSS-2, DFS-2, and New Brief Counterparts",
      journal: "Journal of Sport & Exercise Psychology, 30(5), 561–587",
      doi: "10.1123/jsep.30.5.561",
      itemCount: 9,
      dimensions: ["9つのフロー次元を各1項目で代表"],
      responseFormat: "5件法",
      reverseItems: [], scoring: "9項目の集約的得点。原典を確認。",
      targetPopulation: ["スポーツ・身体活動参加者"],
      language: "English", versionType: "short", parentScaleId: "flow-state-scale",
      japaneseVersionStatus: "related-version",
      japaneseStatusNote: "9項目のShort FSS-2そのものの日本語版は未登録です。ただし、基礎となる長尺版FSS-2には検証済み日本語版があります。",
      japaneseEvidence: [
        { kind: "related-version", label: "長尺版FSS-2の検証済み日本語版", authors: "Kawabata, Mallett, & Jackson", year: 2008, title: "The Flow State Scale-2 and Dispositional Flow Scale-2: Examination of factorial validity and reliability for Japanese adults", doi: "10.1016/j.psychsport.2007.05.005", url: "https://doi.org/10.1016/j.psychsport.2007.05.005" },
      ],
      validationStudies: [], usagePermission: "unknown",
      itemPublicationStatus: "not-published", items: [],
      notes: "36項目版を使えない場合の短縮選択肢。状態版と特性版の短縮尺度が検証された。",
      recordStatus: "verified-metadata",
    },
  ],
};
